### ISSUE TITLE
debug@2.6.0 override not working

### ISSUE THREAD

**Issue by perrin4869** [jspm/registry#1024]
I did:

```bash
rm ~/.jspm
jspm uninstall debug
jspm install debug
```

Inside a jspm project, however, the following is obtained:

```bash
$ cat jspm_packages/npm/debug@2.6.0.json                                                                                                                                 
{
  "main": "browser.js",
  "format": "cjs",
  "map": {
    "./browser.js": {
      "node": "./node.js"
    },
    "fs": "@node/fs",
    "net": "@node/net",
    "tty": "@node/tty",
    "util": "@node/util"
  }
}
```

which is not the override defined in this repository [here](https://github.com/jspm/registry/blob/master/package-overrides/npm/debug%402.6.0.json)

What could be the problem? Thanks!

**Comment by aluanhaddad** [comment]
Do you have an existing override? 
Try `jspm install npm:debug --force`

**Comment by guybedford** [comment]
`jspm install npm:debug -fo` can also be used here to force update the override from the original override as well.

**Comment by perrin4869** [comment]
I see! Yeah the problem was the override inside the `package.json`... maybe it'd be a good idea to make `-fo` a default?

**Comment by guybedford** [comment]
The `-o` option is basically just to reset to an empty override. By default the existing override is maintained to ensure that once you install with an override it doesn't change. That is necessary to keep installs consistent.

**Comment by perrin4869** [comment]
hm... why add the segment to `package.json` when doing `jspm install npm:debug` then?

**Comment by guybedford** [comment]
That is exactly the override - the override used at install time is stored as a constant of the build so that subsequent installs are complete replications.

**Comment by perrin4869** [comment]
hm... what about the cases where it's not constant?
It seems to me like the `override` section in `package.json` should be reserved for manual overrides only, while overrides that come from the registry should remain in `jspm.config.js` only, since they may change during upgrade

**Comment by guybedford** [comment]
This is what we did in jspm 0.16, but changed this in 0.17 because otherwise registry overrides can never be changed without breaking someone's build (which happened a few times before).

**Comment by perrin4869** [comment]
hm... I fail to see how that would break someone's build. If they are relying on the registry's overrides, and the registry override is updated correctly, how could the build break?

**Comment by guybedford** [comment]
Most override _changes_ are backwards-incompatible.

**Comment by perrin4869** [comment]
hm... I think I need an example to figure this one out.
Anyways, this issue is solved now, thanks!
