### ISSUE TITLE
some fetch errors while making ts bundle

### ISSUE THREAD

**Issue by genyklemberg** [jspm/registry#1060]
When I try this command: ` jspm bundle src/main.ts src/build.js`
I receive such an error: 
```
err  Error on fetch for npm:@angular/platform-browser@4.4.4/animations.js at file:///C:/Users/Genyklemberg/code/other project/ngLanding/jspm_packages/npm/@angular/platform-browser@4.4.4/animations.js
  Loading app/app/app.module.ts
  Loading app/main.ts
  Error: ENOENT: no such file or directory, open 'C:\Users\Genyklemberg\code\other project\ngLanding\jspm_packages\npm\@angular\platform-browser@4.4.4\animations.js'
```

Seems like it looks for animations.js file, but I only have animations.d.ts there

**Comment by aluanhaddad** [comment]
This seems to be working correctly but I did not dive deep usage, just verified that the `package.json:main` is discovered and loaded. Would you be able to share a bit of additional information such as your JSPM config and version and an example of how you are using the package?
