### ISSUE TITLE
Latest d3 breaks jspm install

### ISSUE THREAD

**Issue by rockResolve** [jspm/registry#1062]
The latest d3 (4.11.0) breaks jspm install at runtime with "Error: (SystemJS) Node child_process module not supported in browsers."

This is caused by d3 package.json main: "build/d3.node.js"

Workaround 
add jspm override with: jspm -o d3 "{main: 'build/d3.js'}"

See https://github.com/d3/d3-request/issues/24
https://github.com/gatsbyjs/gatsby/issues/2107#issuecomment-330076798

**Comment by guybedford** [comment]
If you'd like to commit this override to the registry with a PR that would be great.

Does the override `{ browser: './build/d3.js' }` work? I'm surprised that isn't already the browser option though or why that isn't triggering.

**Comment by rockResolve** [comment]
Yes your browser override is better and works: jspm install d3 -o "{browser: './build/d3.js'}"
PR created

**Comment by guybedford** [comment]
@rockResolve thanks, I don't see the PR here though?
