### ISSUE TITLE
Question: how much can I use dev.jspm.io?

### ISSUE THREAD

**Issue by mizchi** [jspm/registry#1081]
I made https://github.com/mizchi/trans-loader
It transforms import path to `dev.jspm.io` and cache them in service-worker.

I know `dev.jspm.io` is development only so I added caching feature,  but this use case may cause traffic to dev.jspm.io if many people use this.

Sometimes I watched jspm.io is down in my development. So I want to know, how much can I use dev.jspm.io?

**Comment by guybedford** [comment]
The CDN is definitely designed to be production-level even if the workflows aren't. Stability and uptime at scale is a primary priority.

It would be great to get some details on what downtime you saw during development.

**Comment by mizchi** [comment]
OK. I believe so.
