### ISSUE TITLE
@shopify/app-bridge-utils is missing all new versions for the last 9 months

### ISSUE THREAD

**Issue by jagthedrummer** [jspm/registry#1090]
I'm trying to use the `@shopify/app-bridge-utils` package via importmaps in a Rails project, but when I do `pin @shopify/app-bridge-utils` I end up with a version that is 9 months old (`2.0.16`). If I try to specify a newer version the `pin` command errors out, which seems to be due to jspm not having newver versions of the package.

I opened an issue with Shopify (https://github.com/Shopify/shopify-app-bridge/issues/162), but they seem to think it's a problem with jspm.

Any guidance about how to debug and/or resolve the problem would be greatly appreciated.

**Comment by guybedford** [comment]
Thanks for posting, `shopify/app-bridge-utils` had been automatically flagged as a slow build on the system and disabled. I've reeneabled it and it should be working now.

**Comment by jagthedrummer** [comment]
Thank you, @guybedford! 🙇
