### ISSUE TITLE
Adding some mocha here

### ISSUE THREAD

**Issue by douglasduteil** [jspm/registry#119]
Hi @guybedford

Like I was a bit lost and uncertain of what is actually registered here I wrote some tests (:

I made a little poke and find out that [19 over 155 packages are broken](https://travis-ci.org/douglasduteil/registry/builds/47653659)
( testing made by `curl` the GitHub API).

It would be cool to validate PR and auto check semver format for example (following #118)

What you think ?

**Comment by guybedford** [comment]
@douglasduteil nice, it would definitely be good to have some checks in place. You're right - things like validating the package.json formatting, semver formatting, shim use etc against basic schemas would be ideal.

Note that GitHub repos get moved, that is a fact of life, and why the `jspm install` function supports GitHub redirects.

**Comment by douglasduteil** [comment]
:+1: 


> Note that GitHub repos get moved, that is a fact of life, and why the jspm install function supports GitHub redirects.

Right. I'll send you a PR with my current code.
From what I read you're directly requesting the repo page for that right ?
https://github.com/jspm/github/blob/0.9.11/github.js#L226

**Comment by guybedford** [comment]
We've got full registry validation through Travis now thanks to @2fd.
