### ISSUE TITLE
breezejs

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#133]
Putting this here to track the override so it isn't forgotten. Thanks @jdanyow for working this out.

```
jspm install github:Breeze/breeze.js -o "{ main: 'build/breeze.min.js', dependencies: { jquery: '^2.1.0', Q: 'npm:q' }, shim: { 'build/breeze.min': { deps: ['jquery', 'Q'] } } }"
```

**Comment by jdanyow** [comment]
The original override seemed like it worked initially.  When you do something that uses ajax or promises you find out quickly that breeze doesn't have it's Q and jQuery dependencies.

Here's a similar override that uses npm which results in a lighter download than the github endpoint:

```bash
jspm install npm:breeze-client -o "{ directories: { lib: 'build' }, main: 'breeze.min.js', format: 'amd', dependencies: { jquery: '^2.1.0', Q: 'npm:q' }, shim: { 'breeze.min': { deps: ['jquery', 'Q'] } } }"
```

I'm seeing the Q and jQuery scripts download in the network tab.  Haven't been able to figure out why breeze isn't able to pick them up.

Thinking it has to do with the way breeze does [this](https://github.com/Breeze/breeze.js/blob/master/build/breeze.debug.js#L10-L21), [this](https://github.com/Breeze/breeze.js/blob/master/build/breeze.debug.js#L6211) and [this](https://github.com/Breeze/breeze.js/blob/master/build/breeze.debug.js#L415-L446).

*note: I tested the above override with every `format` option*

**Comment by guybedford** [comment]
It sounds like Q isn't defining into the window global, which is the way breeze expects to find it?

**Comment by jdanyow** [comment]
To test, I installed the unminified version of breeze:

```bash
jspm install npm:breeze-client -o "{ directories: { lib: 'build' }, main: 'breeze.debug.js', format: 'amd', dependencies: { jquery: '^2.1.0', Q: 'npm:q' }, shim: { 'breeze.debug': { deps: ['jquery', 'Q'] } } }"
```

I hit breakpoints in both Q and jQuery to confirm they were being loaded.  When I arrived at a breakpoint in breeze, neither Q or jQuery were defined:

![debugger](http://i.imgur.com/Y7wkVoG.png)

Later on, some application code uses breeze to make an ajax call.  At this point, "Q" is defined, although not on the window object:

![debugger](http://i.imgur.com/qFBPmnO.png)

**Comment by guybedford** [comment]
Yes it should have `window.Q` and `window.jQuery` defined - I'm not sure why they're not.

If you look at the top of the source file, can you see the shim? It should look like `"deps jquery"`.

**Comment by jdanyow** [comment]
yep:
```
"format global";
"deps jquery";
"deps Q";
```

**Comment by guybedford** [comment]
That looks right. I'd be suprised if window.jQuery and window.Q are not defined with the above settings. If you add a console.log right after to check if they are what do you get? If you just import jQuery or Q on their own, can you see them defined on Window?

**Comment by jdanyow** [comment]
I restarted with new package.json, config.js, etc- here's what I'm seeing:  [56 second screencast](http://screencast.com/t/AVsnAZwDQfW).

window.jQuery IS defined.  window.Q is not.  When I import Q by itself it's not defined on window either.

I must have screwed something during all the testing I was doing- it's like you've said all along, issue is related to Q.

**Comment by guybedford** [comment]
@jdanyow thanks for persevering on this. Right so you need to ensure Q is defining onto the window. And because we're loading it from npm, it's not defining onto the window as this isn't the common practice for CommonJS modules.

That's why I'd suggest checking which version of Q bower uses and look at using that, as that version would be designed for the browser and set to define the global.

**Comment by jdanyow** [comment]
bower is installing 2.0.2- same as what jspm has been installing:
![bower](http://i.imgur.com/LGBQVRC.png)

Took a look at the Q 2.0.2 code, couldn't see any place where it defined a global.  The Q readme say v2 is experimental.

Decided to test with Q 1.1.2, used this override:
```bash
jspm install npm:breeze-client -o "{ directories: { lib: 'build' }, main: 'breeze.debug.js', format: 'global', dependencies: { jquery: '^2.1.0', Q: 'npm:q@1.1.2' }, shim: { 'breeze.debug': { deps: ['jquery', 'Q'] } } }"
```

This seemed like a long shot, the [Q 1.1.2 source](https://github.com/kriskowal/q/blob/v1/q.js#L32) says it only creates a global when loaded via a script tag:
![Q source](http://i.imgur.com/NtjELNA.png)

Ended up here when debugging this:
![debugging Q](http://i.imgur.com/GyIE901.png)


Previously I had reported the jQuery was defined when stopped at a breakpoint on the "deps.." shims.  Lately I've been testing by backing out everything in my config.js and packages.config, deleting my jspm_packages folder, running a fresh install, etc.  This probably isn't necessary but it's helpful to assure myself that I'm testing from a "clean" spot.  

I'm now seeing both jQuery and Q are **not** defined.

Here's a quick 1.5 minute screencast of me running through the steps to clean up, install and debug this:
http://screencast.com/t/z37xFrbXK

I'm probably doing something silly- I'm a noob on the git/gulp/jspm/etc scene.

**Comment by guybedford** [comment]
@jdanyow try using q from GitHub instead of npm.

**Comment by guybedford** [comment]
You want Q to load as a global, so you probably want to override the GitHub version with "format": "global".

**Comment by jdanyow** [comment]
Before I do that- did you see this:  http://screencast.com/t/z37xFrbXK

Am I doing something silly?  Why isn't jQuery defined?

**Comment by guybedford** [comment]
@jdanyow it looks like you're using jQuery from npm, which would cause the same issue as with Q - it won't define the global. I'd suggest doing `jspm install jquery -f`.

**Comment by jdanyow** [comment]
ok- that makes sense, given all this is to create a package override for breeze, is it possible to express what you're suggesting in the override syntax?

In other words, people won't explicitly be installing jQuery or Q, they'll be executing `jspm install breeze-client` which in turn needs to bring in jQuery and Q in a way that will work for breeze.

```bash
jspm install npm:breeze-client -o "{ directories: { lib: 'build' }, main: 'breeze.debug.js', format: 'global', dependencies: { jquery: '^2.1.0', Q: 'npm:q@1.1.2' }, shim: { 'breeze.debug': { deps: ['jquery', 'Q'] } } }"
```

**Comment by guybedford** [comment]
@jdanyow so the point is that you need to first create the override for Q, so that you can create the override for breeze:

```
jspm install npm:q -o "{ shim: { 'path/to/q': { exports: 'Q' } } }"
jspm install npm:breeze-client -o "{ directories: { lib: 'build' }, main: 'breeze.debug.js', format: 'global', dependencies: { jquery: '^2.1.0', Q: 'npm:q@1.1.2' }, shim: { 'breeze.debug': { deps: ['jquery', 'Q'] } } }"
```

Something like that? Sorry I can't be of more help right now.

**Comment by jdanyow** [comment]
.Hey @guybedford, looks like I won't need a complex package override for breeze after all..

@wardbell recommended replacing breeze's standard ajax adapter and promise implementations with implementations that use ES6 promises and aurelia's http-client.  This way breeze won't have deps on Q and jQuery.

I appreciate the help troubleshooting this.  Apologies for bugging you.

-jd

**Comment by guybedford** [comment]
Great to hear that. Just let me know if you need more help.
