### ISSUE TITLE
auth0-js

### ISSUE THREAD

**Issue by volak** [jspm/registry#153]
auth0-js depends on zuul which has a commit id reference causing
`unable to resolve defunctzombie/stacktrace.js#07e7b95`

Need to override dependencies to:

"dependencies": {
    "Base64": "~0.1.3",
    "debug": "~1.0.4",
    "json-fallback": "0.0.1",
    "jsonp": "~0.0.4",
    "packageify": "^0.2.0",
    "qs": "git://github.com/jfromaniello/node-querystring.git#fix_ie7_bug_with_arrays",
    "reqwest": "^1.1.4",
    "trim": "~0.0.1",
    "winchan": "^0.1.1",
    "xtend": "~2.1.1"
  },

**Comment by guybedford** [comment]
thanks for letting me know, I added the override in https://github.com/jspm/registry/commit/82af02c819d5cd419b8648b1c420fc29c48c5d7e and it should be working now - let me know if you have further issues at all.

**Comment by guybedford** [comment]
Note it is usually advisable to make a PR to the original repo to try and iron out the issue as well too.
