### ISSUE TITLE
auth0

### ISSUE THREAD

**Issue by volak** [jspm/registry#156]
I've abandoned trying to use the npm version because it requires some browserify packaging stuff I don't know how to deal with.

The github package actually comes with a build in `./build/auth0-lock.min.js` and I've been trying to create an override for it here: https://github.com/volak/registry/blob/master/package-overrides/github/auth0/lock%407.1.1.json

I am so close, but need help with the final bit.

If I do this:

```js
System.import("lock").then((auth0) => {
            var lock = new auth0('key', 'instance.auth0.com');
            console.log(lock);
        });
```
It works!

But when I do this:

```js
import {Auth0Lock} from 'lock';
```

Auth0Lock is undefined

**Comment by guybedford** [comment]
Try doing `import Auth0Lock from 'lock'`. This is the recommended syntax for loading CommonJS, AMD and globals from ES6.

**Comment by volak** [comment]
I see! didn't know there was a difference in that syntax
