### ISSUE TITLE
mocha

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#158]
We have `mocha@^1.21.5` working, but not the latest version. It would be good to get an override going for that.

//cc @stuartc

**Comment by tengyifei** [comment]
I'm able to run mocha 2.2.5 in browser with the 1.21.4 override: https://github.com/jspm/registry/blob/master/package-overrides/npm/mocha%401.21.4.json

**Comment by guybedford** [comment]
@tengyifei thanks so much for sharing. I've added the override.
