### ISSUE TITLE
angular-strap

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#160]
From https://github.com/jspm/jspm-cli/issues/483 by @smajl 

After `jspm install angular-strap` and this line in my code `import 'angular-strap'` I realised that the `jspm_packages/github/mgcrea/angular-strap@2.1.6.js` file is missing (does not get created in the process).

So now have to bypass it with:
```javascript
import 'github:mgcrea/angular-strap@2.1.6/dist/angular-strap'
import 'github:mgcrea/angular-strap@2.1.6/dist/angular-strap.tpl'
```
Is that problem with jspm, angular-strap package definition or something on my side?

**Comment by guybedford** [comment]
@smajl this sounds like a `main` needs to be set in the package.json.

You can do this with an override on install with:

```
  jspm install github:mgcrea/angular-strap@2.1.6 -o "{ main: 'dist/angular-strap' }"
```

What is the `.tpl` file for?

Let me know if it works and we can add the override into the registry repo here.

**Comment by smajl** [comment]
Above works for the first file, but angular-strap needs both of them (.tpl contains directives templates). The obvious: `jspm install angular-strap -o "{ main: ['dist/angular-strap', 'dist/angular-strap.tpl'] }"` does not work. How should I write the override for both of them? Thanks a lot.

**Comment by guybedford** [comment]
@smajl you can shim the main entry point to be dependent on the other file:

```
  jspm install angular-strap -o "{ main: 'dist/angular-strap', shim: { 'dist/angular-strap': { deps: ['./angular-strap.tpl'] } } }"
```

**Comment by smajl** [comment]
@guybedford Thanks a lot. The final and working command is loading .tpl after the main file:
```
jspm install angular-strap -o "{ main: 'dist/angular-strap.tpl', shim: { 'dist/angular-strap-tpl': { deps: ['./angular-strap'] } } }"
```
Angular strap now working and can be imported with `import 'angular-strap'`.

Just last thing - this override does not seems to get saved anywhere localy. So when someone pulls my project and does `jspm install` he won't be getting what I am until someone modifies this remote registry. Really looking forward for that ability to put overrides into my local package.json. :D

**Comment by guybedford** [comment]
Sure, but overrides need to be central otherwise we all have different meanings for packages. That's kind of why it isn't easy!

Would you mind posting a PR to the registry for this?
