### ISSUE TITLE
Angular loading minified version

### ISSUE THREAD

**Issue by smajl** [jspm/registry#167]
Was there some special intention to override Angular to it's minified version? I really would like to load all my libs unminified during development.

If this is unintended, I will soon prepare a PR which corrects this.

**Comment by andreasgrimm** [comment]
that's what I was asking myself today as well.
I suggest using unminified version if there are no complaints.

**Comment by guybedford** [comment]
Yes we used to use minified versions of all libraries on jspm, but source maps haven't been supported well enough for this yet.

It would be great to switch Angular over to the unminified version.

**Comment by smajl** [comment]
https://github.com/jspm/registry/pull/170
