### ISSUE TITLE
baconjs

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#171]
Would be good to test and confirm the override for this.

**Comment by Jarreddebeer** [comment]
Couldn't find an override for it so i created a new one. https://github.com/jspm/registry/pull/211

Side note, would you like me to merge these in myself or wait for you to vet them first, just in case i break the registry?

**Comment by guybedford** [comment]
Thanks so much. Let's stick with review for now until we've covered the main scenarios at least.

**Comment by guybedford** [comment]
Included in the registry and working I believe.
