### ISSUE TITLE
web-animation-js

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#174]
From https://github.com/systemjs/systemjs/issues/345:

//cc @hgl

```js
import "web-animation-js/web-animations-next.dev";
```

```
$ jspm bundle move/main
Building the bundle tree for move/main...

err  Error: Error loading "web-animation-js/web-animations-next.dev" at file:/Users/hgl/dev/lab/jspm/web-animation-js/web-animations-next.dev.js
     Error loading "web-animation-js/web-animations-next.dev" from "move/main" at file:/Users/hgl/dev/lab/jspm/lib/main.js
     ENOENT, open '/Users/hgl/dev/lab/jspm/web-animation-js/web-animations-next.dev.js'
```

Clearly, jspm is trying to bundle the file from my project root folder (Users/hgl/dev/lab/jspm/).

I have tried another npm package where the main entry point exists, and I can import a specific file like `<pkgname>/<file>` with no problem, but no when the entry point is missing in `package.json`.

**Comment by guybedford** [comment]
@hgl can you perhaps post your config.js file as well to help work out what the issue is here.

**Comment by hgl** [comment]
Sure, and thanks for the help.

```js
System.config({
  "baseURL": ".",
  "transpiler": "6to5",
  "paths": {
    "*": "*.js",
    "move/*": "lib/*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  },
  "bundles": {
    "build": [
      "npm:dom4@1.3.1/build/dom4.max",
      "move/main"
    ]
  }
});

System.config({
  "map": {
    "dom4": "npm:dom4@1.3.1",
    "web-animations-js": "github:web-animations/web-animations-js@1.0.6"
  }
});
```
`dom4` is where i test `import "dom4/build/dom4.max";` and can bundle it successfully.

**Comment by guybedford** [comment]
I think this is just a typo - try importing _web-animation**s**-js_.

**Comment by hgl** [comment]
o_O, I feel so dumb right now.

You are absolutely right. Now I can bundle it. Sorry for wasting your time. I will be more careful next time. :P

**Comment by hgl** [comment]
But maybe a warning could be printed when jspm failed to find the package both in `jspm_packages` and in the root folder? Currently it looks like jspm is doing something wrong, since I want to import a package, and it's searching in the root folder.

**Comment by hgl** [comment]
Or it should mention that it has searched in `jspm_packages`, but failed to find the package.

**Comment by guybedford** [comment]
Good suggestion, I've created https://github.com/ModuleLoader/es6-module-loader/issues/303.
