### ISSUE TITLE
Famous

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#183]
It seems the Famous override isn't working correctly (https://github.com/jspm/registry/blob/master/package-overrides/github/Famous/famous%400.3.0.json).

Note that `*/*` in a shim is not supported as we don't do support globbing, just a single single-depth wildcard.

**Comment by trusktr** [comment]
Updated: https://github.com/jspm/registry/pull/151

**Comment by trusktr** [comment]
Single path wildcard still not working.

**Comment by guybedford** [comment]
@trusktr thanks so much for letting me know, I've fixed the wildcards in https://github.com/jspm/jspm-cli/commit/ee9d5e2f130552e607c139dbcd6793b556a60fb7.
