### ISSUE TITLE
Request: use glob

### ISSUE THREAD

**Issue by trusktr** [jspm/registry#188]
If you could use [glob](https://www.npmjs.com/package/glob) so shims can have things like `./*`, `**/*.js`, or `foo/**/bar/*/baz/*.js`, that'd be great!

**Comment by trusktr** [comment]
I'll gladly go and update every override in the registry that gets broken by this change.

**Comment by guybedford** [comment]
I'd rather not add arbitrary glob shims right now, but have fixed up the standard wildcards (which have been broken for a while!).
