### ISSUE TITLE
ng-infinite-scroll override not being used

### ISSUE THREAD

**Issue by TimPetricola** [jspm/registry#207]
Doing `jspm install ng-infinite-scroll` doesn't load its override:

```
$  sudo jspm install ng-infinite-scroll
     Updating registry cache...
     Looking up github:sroze/ngInfiniteScroll
     Downloading github:sroze/ngInfiniteScroll@1.2.0

warn No main entry point detected for github:sroze/ngInfiniteScroll@1.2.0.
     Try adding an override, or set the package.json "main": false if this is the intention.

ok   Installed ng-infinite-scroll as github:sroze/ngInfiniteScroll@^1.2.0 (1.2.0)
ok   Install tree has no forks.

ok   Install complete.
```

The only way for me to make it work is to use: `jspm install ng-infinite-scroll -o "{ main: 'build/ng-infinite-scroll' }"`.

I couldn't find where in `jspm` the overriding files are being loaded.

Thanks for the help :)

**Comment by guybedford** [comment]
Thanks for posting - yes the override was named incorrectly. I've fixed this in https://github.com/jspm/registry/commit/4448ed129f4531ff41feffe166e004a5e70050bb and it should be working now.

**Comment by TimPetricola** [comment]
Great thanks @guybedford :+1:
