### ISSUE TITLE
Readme: Semver Compatibility?

### ISSUE THREAD

**Issue by speigg** [jspm/registry#208]
> The overrides will apply for all versions semver compatible with the override version, with the highest version override taking precedence.

What does this mean exactly? Does semver compatible include minor version changes or only patch versions? And if I try to install a version of a package that is newer than the override that is in the registry, what happens? For example, if the registry contains an override for version `r70` of three.js, and I try to `jspm install` version `r71`, will jspm use the `r70` override that it knows about? (I hope so, but it's not clear to me). And how are major versions handled?

**Comment by guybedford** [comment]
@speigg we apply the semver range - which is defined as https://github.com/npm/node-semver#caret-ranges-123-025-004.

`r71` won't apply to `r70` because it isn't a valid semver. Major versions don't count. Also prereleases don't count either.

**Comment by speigg** [comment]
Hmm. That doesn't really answers my questions. I understand how semver compatability works, just not what it's role is with overrides. the main thing I'm tying to figure out: if an old override is compatible with a newer version of a library (not semver compatible necesarilly but functionally compatible) does it need to be updated in the registry every time there is a new version of the package? 

For example, let's say we have an override for package X version 0.0.1 in the registry. Is this override used in each of the following situations?

`jspm install X@0.0.2`
`jspm install X@0.1.0`
`jspm install X@1.0.0`

The answer (still) isn't clear to me.

**Comment by guybedford** [comment]
Right, so an override at version 0.0.1 will only apply for version 0.0.1. An override at 0.1.5 will apply for all >=0.1.5<0.2.0-. And an override at 1.0.0 will apply for all <2. Prereleases are excluded, although perhaps we should consider allowing them actually.

**Comment by speigg** [comment]
Okay thanks for clarifying, but that doesn't really make sense to me. 

Assuming that an override for version 0.1.5 would apply for all >=0.1.5<0.2.0
Wouldnt an override for version 0.0.1 apply for all >=0.0.1<0.1.0 ?
Likewise, wouldn't an override for version 1.0.0 apply for all >=1.0.0<0.1.0 ?

**Comment by guybedford** [comment]
No, the ranges I've given are the ranges defined by semver (https://github.com/npm/node-semver#caret-ranges-123-025-004).

The reason everyone publishes version 1 from day 1 is exactly because of this fact that the ranges are reduced below 1, and everyone gets confused about it. It's a pretty simple rule though - we just need someone to share the actual info clearly.

**Comment by speigg** [comment]
Okay, I think I understand now. Thanks for explaining.
