### ISSUE TITLE
can't get lumx from github installed without manually configuring it.

### ISSUE THREAD

**Issue by Hendrixer** [jspm/registry#220]
when I : `jspm github:lumapps/lumx`
I get: 'Try adding an override, or set the package.json "main": false if this is the intention.'

when I : `jspm github:lumapps/lumx -o "{main: 'dist/js/lumx'}"`
I get: 'Try adding an override, or set the package.json "main": false if this is the intention.'
I don't know what the override does exactly, explanation would be great.

To make this work, I go into `jspm_packages/github/lumapps/` and create the appropriate file to `module.exports` the entry file. Then I go into `dist/js/lumx.js` and at the top `"format global";
"exports lumx";` Where `lumx` is the angular module I had to save as a global.

I know this is not the right way to get github repos to work, and there must be something I am missing.

**Comment by guybedford** [comment]
Sure, I think it looks like the main path should be `dist/lumx`? See https://github.com/lumapps/lumX/tree/v0.3.12/dist

**Comment by Hendrixer** [comment]
aha, yup, thanks @guybedford . Also, the docs on the overrides were a bit confusing to me as well. After reading some overrides in the registry, it made sense.

**Comment by kbdaitch** [comment]
@Hendrixer may I ask if you ran into the issue wherein the bourbon dependency in scss is being included using a relative path, assuming a (bower-style) flat dependency path?

I created this: https://github.com/lumapps/lumX/issues/242

Not sure how you navigated the issue?
