### ISSUE TITLE
css from materialize css

### ISSUE THREAD

**Issue by 2fd** [jspm/registry#225]
in relation with #224 and jspm/github#6

the installation command to download the first version,
that not containing the css files. (https://github.com/Dogfalo/materialize/releases)

**Comment by guybedford** [comment]
Right, yes jspm will download the release archive over the repo. We're looking at perhaps separating this option out into a separate install so you can still install from the underlying repo if necessary - is that what you would need?

**Comment by 2fd** [comment]
that would be nice :+1:

**Comment by guybedford** [comment]
You can follow the issue at https://github.com/jspm/github/issues/6.

In the mean time have you managed to find a workaround?

**Comment by 2fd** [comment]
I developed a [bower-endpoint](/2fd/jspm-bower-endpoint)
I'm using it

**Comment by guybedford** [comment]
Nice work! Did you see the discussion at https://github.com/matthewp/jspm-bower/issues/5?
