### ISSUE TITLE
Mithril

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#260]
`jspm install npm:mithril` not working apparently.

**Comment by brynedwards** [comment]
Hi, I just tried this with the latest jspm and ```jspm install npm:mithril``` followed by ```import m from 'mithril'``` all works as expected.

**Comment by guybedford** [comment]
Great, thanks for reporting. Added in https://github.com/jspm/registry/commit/4c0e2cc8127d487627b2e82fea7497fcfc08472e.
