### ISSUE TITLE
Knockout

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#282]
Does it work? If so we should add it to the registry to enable `jspm install knockout`.

**Comment by guybedford** [comment]
From https://github.com/jspm/jspm-cli/issues/600#issuecomment-84414582:

I did a quick test and here are the issues (the repo is available here: https://bitbucket.org/carlosagsmendes/jspm-knockout/src

1) I installed Knockout and Knockout-Validation using Github

jspm install **knockout**=github:knockout/knockout

jspm install **knockout-validation**=github:Knockout-Contrib/Knockout-Validation

*The references on the config file weren't correct. I had to fix them manually since I couldn't load the files:*

```GET http://localhost:8080/lib/github/knockout/knockout@3.3.0.js 404 (Not Found)
es6-module-loader.src.js:140 Potentially unhandled rejection [3] Error loading "github:knockout/knockout@3.3.0" at http://localhost:8080/lib/github/knockout/knockout@3.3.0.js
Error loading "github:knockout/knockout@3.3.0" from "app/knockout-bootstrapper" at http://localhost:8080/app/knockout-bootstrapper.js
Not Found: http://localhost:8080/lib/github/knockout/knockout@3.3.0.js (WARNING: non-Error used)
es6-module-loader.src.js:2563 GET http://localhost:8080/lib/github/knockout/knockout@3.3.0.js 404 (Not Found)```

2) To get it working I had to change the **config.js** manually. I had to fix the paths:

https://bitbucket.org/carlosagsmendes/jspm-knockout/commits/c08a656c6ccd0997360f91e93d57502b63486661#Lconfig.jsF12

3) I need to have KO as a global. I added a **Meta** section to **config.js** but I'm still unable to get *ko* available in the browser console

```
System.config({
    "meta": {
        "knockout": {
            "exports": "ko"
        }
    }
});
```

I may be missing something since I'm just getting started with JSPM. Please advise

**Comment by guybedford** [comment]
@carlosagsmendes Knockout is installing fine for me here actually, detecting the main from the bower.json file - which version of jspm are you running? (`jspm -v` will tell you)

**Comment by guybedford** [comment]
@carlosagsmendes perhaps also try `jspm install -f` to clear the package cache. I may not have bumped the cache version when making a previous patch to the bower handling.

**Comment by carlosagsmendes** [comment]
Thank you @guybedford I'm using 0.14.0

I didn't get why are you mentioning Angular. Is it just to explain the -f option?

**Comment by guybedford** [comment]
Sorry I mean `knockout`!

What I can assure you is that this install works in the next jspm release coming up. `-f` just clears the local package cache re-running the endpoint build operations (like reading the main from the bower.json). Normally you don't need to use it, but I may have forgotten to invalidate the cache from my side.

In the mean time, you can get this to work with:

```
  jspm install github:knockout/knockout -o "{main: 'dist/knockout'}"
```

That's how overrides are designed to work. If that works completely, we add it into the registry repo here, and everyone benefits from it.

**Comment by carlosagsmendes** [comment]
It works @guybedford.

It created a *lib/github/knockout/knockout@3.3.0.js* file with the following content:

```
define(["github:knockout/knockout@3.3.0/dist/knockout"], function(main) {
  return main;
});
```

So should I create a PR on the registry? Would the content be only the following?

```
{main: 'dist/knockout'}
```

Also, do you know why the *meta* section is not working? *ko* is not being exported as a global variable:

```
System.config({
    "meta": {
        "knockout": {
            "exports": "ko"
        }
    }
});
```

My understanding is that I can also make *ko* global by including a shim section on the package override:

```
{
  "main": "dist/knockout",
  "shim": {
    "dist/knockout": {
      "exports": "ko"
    }
  }
}
```

But I would really like to understand why isn't the meta configuration working

Thank you for your help

**Comment by guybedford** [comment]
The meta section has to include the full name `github:knockout/knockout@2.3.4/dist/knockout`, so it can be tricky to do manually.

You can do a shim in the override as well - `jspm install github:knockout/knockout -o "{main: 'dist/knockout', shim: {'dist/knowckout': { exports: 'ko' }}}"`

If that works, a PR to the registry would be amazing.

**Comment by carlosagsmendes** [comment]
Sure. I will submit two, one for Knockout and another for Knockout-Validation. 

I want to add a map from *knockout/knockout* to *knockout*

This is what I do on the command line:
```
jspm install knockout=github:knockout/knockout -o "{main: 'dist/knockout', shim: {'dist/knockout': { exports: 'ko' }}}"
```

1) Can I add an entry to the registry.json, for the mapping? Or can I also do the mapping on the package override?

2) Since I will be referrencing the source file for Knockout should I also include a buildConfig section? To ensure that it gets minified?

```
"buildConfig": {
    "minify": true
  }
```

**Comment by guybedford** [comment]
That would be really great, thanks!

Yes if you add `"knockout": "github:knockout/knockout"` to the registry.json in the PR, then that will mean that:

```
  jspm install knockout
```

does exactly the same thing as:

```
  jspm install knockout=github:knockout/knockout
```

Note the `buildConfig` section is no longer supported.

**Comment by carlosagsmendes** [comment]
https://github.com/jspm/registry/pull/285

So should we minify during our bundling process? Or is it best to have another map in the production configuration file and point to the minified file instead? 

Also, is there anything else I should do for people using Knockout from Bower? Apparently there are only folders for NPM and Github packages in the registry, but I've seen the following:

**bower-**angular@1.3.0.json

Is this the right way to create a package override for people using bower?

**Comment by guybedford** [comment]
Yes exactly - minification can happen as part of the build process. When bundling use the `-m` option to minify.

The `bower-angular` is because that is the name of the repo we use for angular. The knockout repo you posted is the right one to use.

Now you can try the Knockout validation one with a similar override like `jspm install github:knockout-validation/knockout-validation -o "{dependencies: { knockout: 'github:knockout/knockout@^3.3.0' }}"`. Let me know if you need any help for that one at https://github.com/jspm/registry/issues/283.

**Comment by carlosagsmendes** [comment]
Here you go https://github.com/jspm/registry/pull/286

Thanks a bunch!
