### ISSUE TITLE
Package Overrides - Define Specific version

### ISSUE THREAD

**Issue by carlosagsmendes** [jspm/registry#294]
I created a package override for knockout. The file name is *knockout@3.3.0.json*

You can take a look at the file [here](https://github.com/jspm/registry/tree/master/package-overrides/github/knockout)

I also created an entry on the registry
`"knockout": "github:knockout/knockout"`

When I do a **jspm install knockout** I get the following in my packages.config:

`"knockout": "github:knockout/knockout@^3.3.0"` 

What do I have to do to ensure that my packages.config will have a reference to a specific version? `github:knockout/knockout@`**=**`3.3.0"`

Thanks

**Comment by guybedford** [comment]
`jspm install knockout@3.3.0` or `jspm install knockout=3.3.0` should both work.

**Comment by carlosagsmendes** [comment]
Thks
