### ISSUE TITLE
Shim (and main and map?) are not being treated relative to directories.lib.

### ISSUE THREAD

**Issue by trusktr** [jspm/registry#297]
The wiki for [`directories.lib`](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#directorieslib) says

> All file paths will now be relative to this lib folder, including for use in the other package configuration options such as main, shim and map.

So if I have `"deps": ["core/famous.css!"]` I noticed it causes jspm to look for `/core/famous.css` from the root of the domain, *not* relative to `directories.lib`. The current solution is to use a relative path like `"deps": ["../core/famous.css!"]`, which ends up working, f.e., this doesn't work:

```js
  "format":"amd",
  "jspm": {
    "registry":"jspm",
    "directories": {
      "lib": "src"
    },
    "dependencies": {
      "css": "^0.1.0",
      "famous-polyfills": "npm:famous-polyfills"
    },
    "shim": {
      "core/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      },
      "events/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      },
      "inputs/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      },
      "math/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      },
      "modifiers/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      },
      "physics/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      },
      "surfaces/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      },
      "transitions/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      },
      "utilities/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      },
      "views/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      },
      "widgets/*": {
        "deps": ["core/famous.css!", "famous-polyfills"]
      }
    }
  }
```

but this does:

```js
  "format":"amd",
  "jspm": {
    "registry":"jspm",
    "directories": {
      "lib": "src"
    },
    "dependencies": {
      "css": "^0.1.0",
      "famous-polyfills": "npm:famous-polyfills"
    },
    "shim": {
      "core/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      },
      "events/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      },
      "inputs/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      },
      "math/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      },
      "modifiers/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      },
      "physics/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      },
      "surfaces/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      },
      "transitions/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      },
      "utilities/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      },
      "views/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      },
      "widgets/*": {
        "deps": ["../core/famous.css!", "famous-polyfills"]
      }
    }
  }
```

**Comment by guybedford** [comment]
`deps` behaves just like writing a require inside of the module itself. So imagine you are writing `import "core/famous.css!"`

**Comment by trusktr** [comment]
@guybedford Oh, so can the module refer to itself like 

```js
      "widgets/*": {
        "deps": ["famous/core/famous.css!", "famous-polyfills"]
      }
```

?

**Comment by trusktr** [comment]
Yep, that worked too! But I think it'd break if I name `famous` something else in my apps `config.js`.

**Comment by trusktr** [comment]
The registry wiki for [shim](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#shim) says that

> Shims aren't limited to globals and can be used to define the dependencies for any file in a project.

I put that there, but it's (partially) true since I'm able to get it working with relative paths or module paths, just not relative to `directories.lib`.

Ideally it should be either entirely supported for all formats (rather than half way) or entirely not supported except for global format (i.e. completely ignored for other formats).

But I'd say just get it working with all formats. It's probably really easy for you to do!

**Comment by trusktr** [comment]
The premise is this: no one will ever want to use famous without the famous stylesheet. It doesn't make sense, so why not preload it in a shim like this? And many people also don't want to worry about whether the code works, they just want it to work, so hence the polyfills (no problem there since it's a module name).

**Comment by guybedford** [comment]
If you'd like to change the override, you need to convince the other users of the Famous override that this is necessary. I'm not really in a position to judge.

**Comment by trusktr** [comment]
That aside, I simply meant that in the general case shims should work identically with all formats.
