### ISSUE TITLE
How to add files to bundle?

### ISSUE THREAD

**Issue by nd0ut** [jspm/registry#299]
Hello!

Here is the [flummox](https://github.com/acdlite/flummox) package.

There are `Flux.js` in `main` section, which requires two near files: `Actions.js` and `Store.js`. So when I do `jspm bundle` it handles these files and their external dependencies. Ok.

Now I need to bundle also file `addons/FluxComponent.js` which is not dependency of any of these files above. How can I do that?

**Comment by guybedford** [comment]
You can do this with bundle arithmetic:

```
  jspm bundle main + addons/FluxComponent
```

**Comment by nd0ut** [comment]
@guybedford thanks
