### ISSUE TITLE
Is there a way to hide variables using package overrides?

### ISSUE THREAD

**Issue by nathanathan** [jspm/registry#303]
When I try to use SystemJS to to import Ace into an environment that has already has the require variable defined (in this case the c9.io editor), I encounter an error. I have been able to work around it by temporarily setting require to null until Ace loads. Is there a way to make the Ace package override to do this? Or is there a better way to solve this kind of problem?

**Comment by guybedford** [comment]
Good idea - I've added this in https://github.com/systemjs/systemjs/commit/98c3de60be24b119f8ca38b1c446ea1b0c74927b. You can test it with `jspm dl-loader --edge`.

**Comment by nathanathan** [comment]
I tried the following:

1. Run `jspm dl-loader --edge` and `jspm install ace`
2. Start a node express server that hosts all the files in my workspace with CORS enabled.
3. In my browsers terminal while in the c9 ide:
```javascript
var js = document.createElement("script");
js.type = "text/javascript";
js.src = "https://github.jspm.io/jmcriffey/bower-traceur@0.0.79/traceur.js";
document.body.appendChild(js);
```
```javascript
var js = document.createElement("script");
js.type = "text/javascript";
js.src = "https://github.jspm.io/ModuleLoader/es6-module-loader@0.10.0/dist/es6-module-loader.js";
document.body.appendChild(js);
```
```javascript
var js = document.createElement("script");
js.type = "text/javascript";
js.src = "https://preview.c9.io/user/workspace/jspm_packages/system.js";
document.body.appendChild(js);
```
```javascript
var js = document.createElement("script");
js.type = "text/javascript";
js.src = "https://preview.c9.io/user/workspace/config.js";
document.body.appendChild(js);
```
```javascript
System.baseURL = "https://workspace-user.c9.io/";
System.import("ace/ace").then(console.log.bind(console));
```

I ended up with this error:
```
Uncaught ReferenceError: ace is not defined
Uncaught (in promise) Error loading "github:ajaxorg/ace-builds@1.1.8/ace" at https://workspace-user.c9.io/jspm_packages/github/ajaxorg/ace-builds@1.1.8/ace.js
Error evaluating https:///workspace-user.c9.io/jspm_packages/github/ajaxorg/ace-builds@1.1.8/ace.js
Uncaught ReferenceError: ace is not defined
```

**Comment by guybedford** [comment]
See https://github.com/jspm/registry/issues/38#issuecomment-72440841 for how to get Ace working through jspm, hopefully that should help.

**Comment by guybedford** [comment]
I've been trying to test this as well, but the GitHub availability is so bad I can't get the install to work - will try again later.

**Comment by guybedford** [comment]
I'm not sure this is just require conflicting? I tried creating a require in my project with:

```html
<!doctype html>
  <script src="jspm_packages/system.src.js"></script>
  <script src="config.js"></script>
  <script>
    var require = function() {};
    System.import('ace/ace').then(function(m) {
      console.log(m);
    });
  </script>
```

And it was still loading fine. Perhaps see if you can work out how to replicate the conflict condition in a blank project so we can know for sure what it is.
