### ISSUE TITLE
Is it possible to test package overrides in my browser's console?

### ISSUE THREAD

**Issue by nathanathan** [jspm/registry#304]
I think it would be convenient to be able to test package overrides by using JS commands like this in my browser's console:

```javascript
System.packageConfiguration("github:twbs/bootstrap", { main: 'js/bootstrap', shim: { 'js/bootstrap': ['jquery'] } })
System.import("github:twbs/bootstrap")
```

Does SystemJS have a feature like this, and if not, would it be a reasonable thing to add in the future?

**Comment by guybedford** [comment]
You can test out shims with:

```javascript
System.meta['github:twbs/bootstrap/js/bootstrap'] = { deps: ['jquery'], format: 'global' };
```

for example.

Setting mains can be done with:

```javascript
System.map['github:twbs/bootstrap'] = 'github:twbs/bootstrap/js/bootstrap';
```

But the syntax is SystemJS-specific not the jspm package format as these are separate levels. This configuration will be changing over time though, and may or may not correlate more in future.

**Comment by nathanathan** [comment]
Thanks for the help!
