### ISSUE TITLE
JSPM config for Semantic-ui

### ISSUE THREAD

**Issue by eliorcohen** [jspm/registry#306]
hey,

i was trying to create a definition file for   [semantic-ui](https://github.com/Semantic-Org/Semantic-UI "semantic-ui")   based on the bootstrap example.
i forked the semantic-ui and add the adjustments, but it's seems that the jspm cli from some reason don't retrieve the updates i have made.

i used the chace-clear command and the -f flag without success..
i'm using version 0.15.1

this is the command i run to add the lib
```
jspm install github:eliorcohen/semantic-ui
```

i have added this code into the package.json file hoping it will work:
```
"main": "./dist/npm",
"jspm": {
    "main": "semantic",
    "shim": {
      "semantic": {
        "deps": "jquery",
        "exports": "$"
      }
    },
    "files": ["components", "themes"]
  }
```

thanks,
Elior

**Comment by guybedford** [comment]
@eliorcohen note that jspm will install the latest stable tag version. You probably want to use `jspm install github:eliorcohen/semantic-ui@master` to get this to work.

Note you can get the same with:

`jspm install github:Semantic-Org/Semantic-UI -o "{main: 'semantic',shim:{semantic: {deps: 'jquery', exports: '$'}}}"`

Do send a PR here with the override if you get it working, it would be useful to have.

**Comment by eliorcohen** [comment]
i ended up using 

```
jspm install github:semantic-org/semantic-ui -o "{ main:'./dist/semantic', shim: { 'semantic-org/semantic-ui' : { deps: ['jquery'], exports: '$' } } }"
```
this load the js file successfully, but i cant find a way to inject the related css files, i tried to add the 'files' attribute with the override flag, but it's throwing me a warning that the main entry point is not defined...

**Comment by eliorcohen** [comment]
i have also noticed that the module don't export anything..
if i'm manually add the **"exports $";** deceleration in the js file (the **"format global";** is automatically inserted).

semantic.js file
```
/* */
"format global";
"exports $";
 /*
 * # Semantic UI - 1.11.6
```
app.js file
```
import {Router} from 'aurelia-router';
import bootstrap from 'bootstrap';
import semantic from 'semantic-org/semantic-ui';

export class App {
  static inject() { return [Router]; }
    constructor(router) {
      
      // this will return an empty object unless i will
      // manually inject the 'exports $'; to the js lib file.
      console.log('semantic:',semantic);

    this.router = router;
    this.router.configure(config => {
      config.title = 'Aurelia';
      config.map([
        { route: ['','index'],  moduleId: './index',      nav: true, title:'Index' }
      ]);
    });
  }
}
```


i think i'm doing something wrong with the shim config, i have no past experience with require/amd modules and this is very confusing..

i have manage to get the same result with this command:

```
jspm install github:semantic-org/semantic-ui -o "{ main:'semantic', directories: { lib: 'dist' } }"
```

so the shim dose not really effect anything.. 

thanks,
elior

**Comment by eliorcohen** [comment]
i think i finally got it to work,

i was needed to delete the jspm folder and install jquery and css locally as a dependency (something the the bootstrap package dose not do... ) after lot's of error and warning like:

```
jspm install jquery
     Updating registry cache...
     Looking up github:components/jquery
     Looking up github:semantic-org/semantic-ui
     Downloading github:semantic-org/semantic-ui@1.11.6
ok   Up to date - jquery as github:components/jquery@^2.1.3 (2.1.3)
ok   Install tree has no forks.

err  Registry githubjspm not found.

err  Unable to load registry githubjspm

warn Installation changes not saved.

```
and

```
jspm install github:semantic-org/semantic-ui -o "{ main:'dist/semantic', shim: { 'dist/semantic' : { deps: ['jquery'], exports: '$' } }, dependencies: { jquery: '*' } }"
     Looking up github:semantic-org/semantic-ui
     Updating registry cache...
     Downloading github:semantic-org/semantic-ui@1.11.6
     Looking up github:jquery

warn Repo github:jquery not found!

err  Repo github:jquery not found!

```

 
i used this command:

```
jspm install github:semantic-org/semantic-ui -o "{ main:'dist/semantic', shim: { 'dist/semantic' : { deps: ['jquery','./semantic.css\!'], exports: '$' } }, dependencies: { jquery: '*', css: '*' } }"
```

this will load the js file and export it to the main app and load the css,
i'm still not happy about the local jquery dependence registration and like to know how to set the dependency on the package itself like the bootstrap package..   

i will test it in the morning, it's not 4am local time, after bashing my head around it for more then 5 hours...

**Comment by glen-84** [comment]
This works:

    jspm install semantic-ui=github:Semantic-Org/Semantic-UI -o "{ 'directories': { 'lib': 'dist' }, main: 'semantic', 'shim': { 'semantic': { 'deps': [ 'jquery', 'semantic-ui/semantic.css!' ] } }, 'dependencies': { 'jquery': 'github:components/jquery', 'css': 'github:systemjs/plugin-css' } }"

```JavaScript
    "overrides": {
      "github:Semantic-Org/Semantic-UI@1.11.8": {
        "directories": {
          "lib": "dist"
        },
        "main": "semantic",
        "shim": {
          "semantic": {
            "deps": [
              "jquery",
              "semantic-ui/semantic.css!"
            ]
          }
        },
        "dependencies": {
          "jquery": "github:components/jquery",
          "css": "github:systemjs/plugin-css"
        }
      }
    }
```

Notes:

1. I don't understand what the shim exports is for, so I didn't include it.
2. There is an [FOUC](http://acronyms.tfd.com/FOUC) when you load the CSS in this way, so it's probably better to exclude the CSS file and load it directly instead.

**Comment by guybedford** [comment]
@glen-84 thanks for posting, I'll test this out to see if we can get this into the registry overrides so all users get it. Also nice to see you're in Cape Town too :)

**Comment by guybedford** [comment]
I've created the PR for this in https://github.com/jspm/registry/pull/332.

**Comment by glen-84** [comment]
Thanks Guy. :smiley:

**Comment by guybedford** [comment]
Added in https://github.com/jspm/registry/pull/332.
