### ISSUE TITLE
Errors installing with NPM after updating `package.json`

### ISSUE THREAD

**Issue by ThomasBurleson** [jspm/registry#348]
Per recent suggestions, I updated the `package.json` for Angular Material Deployment repository [/angular/bower-material](https://github.com/angular/bower-material/blob/master/package.json). Those updates improved configuration for installs with **jspm**:

Package.json:

```json
{
  "name": "angular-material",
  "version": "0.9.0-rc1-master-9fc2c28",
  "main": "index",
  "format":"cjs",
  "registry": "jspm",
  "dependencies": {
    "angular": "github:angular/bower-angular@^1.3.15",
    "angular-animate": "github:angular/bower-angular-animate@^1.3.15",
    "angular-aria": "github:angular/bower-angular-aria@^1.3.15",
    "css": "github:systemjs/plugin-css@^0.1.9"
  },
  "shim": {
    "angular-material": {
      "deps": [ "./angular-material.css!" ]
    }
  },  
  "peerDependencies": {
      "angular": "^1.3.0 || >1.4.0-beta.0",
      "angular-animate": "^1.3.0 || >1.4.0-beta.0",
      "angular-aria": "^1.3.15 || >1.4.0-beta.0"
  }
}
```

With these change I can use jspm to install directly from that repository:  

```console
> jspm install angular-material=github:angular/bower-material@0.9.0-rc1`
```

But now NPM installs complain with

```console
> npm install angular/bower-material

Unsupported URL Type: github:angular/bower-angular-animate@^1.3.15
```

So I removed the `shim` and `dependencies` sections so NPM can use the Peer Dependencies. 

```json
{
  "name": "angular-material",
  "version": "0.9.0-rc1-master-55fa76a",
  "main": "index",
  "format":"cjs",
  "registry": "jspm",
  "peerDependencies": {
      "angular": "^1.3.15",
      "angular-animate": "^1.3.15",
      "angular-aria": "^1.3.15"
  }
}
```

But now my JSPM install suffers. 

#### Question:

How can I resolve my repository `package.json` to support both JSPM with shims and NPM?

**Comment by guybedford** [comment]
The way to do this is by using the `jspm` property in the package.json for properties that are unique to jspm:

```json
{
  "dependencies": {
    "node": "dependencies"
  },
  "jspm": {
    "dependencies": {
      "jspm": "dependencies"
    }
  }
}
```

The other thing to do is only reference packages on npm itself, and then set the `registry: npm` property in the package. Effectively writing a "Node/npm" style package only without any jspm features.

Let me know if that makes sense.

**Comment by ThomasBurleson** [comment]
LOL. Let me try to interpret; would the below be correct ?

```json
{
  "name": "angular-material",
  "version": "0.9.0-rc1-master-4fbae86",
  "main": "index",
  "format":"cjs",
  "registry": "jspm",
  "peerDependencies": {
      "angular": "^1.3.15 || >1.4.0-beta.0",
      "angular-animate": "^1.3.15 || >1.4.0-beta.0",
      "angular-aria": "^1.3.15 || >1.4.0-beta.0"
  },
  "jspm" : {
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.3.15",
      "angular-animate": "github:angular/bower-angular-animate@^1.3.15",
      "angular-aria": "github:angular/bower-angular-aria@^1.3.15",
      "css": "github:systemjs/plugin-css@^0.1.9"
    },
    "shim": {
      "angular-material": {
        "deps": [ "./angular-material.css!" ]
      }
   }
}
```

**Comment by guybedford** [comment]
Yes! Note that jspm will try and pick up the peerDependencies as well in future, so you may want to set that to an empty object in the jspm sub-object.

**Comment by ThomasBurleson** [comment]
I updated the struct above for peerDependencies. What about the 'registry' key. is that correct or should it be in the 'jspm' object?

**Comment by guybedford** [comment]
Note peer dependencies shouldn't be inside the shim.

The registry key isn't strictly necessary here actually, although if you set it to `github`, that can simplify the representation of your dependencies to not need the `github:` in all of them.

**Comment by ThomasBurleson** [comment]
Like this?

**Comment by guybedford** [comment]
Yes, that looks great.

**Comment by guybedford** [comment]
Note you can include shim at the base-level if you prefer - the jspm property just "overrides".

**Comment by ThomasBurleson** [comment]
In my mind the shim is only used by JSPM for the css plugin; hence its nesting.

**Comment by ThomasBurleson** [comment]
Awesome. Thanks for all your support and amazing fast responses.
I will update and test on my end. Once that looks good. I will post a blank package override.

**Comment by guybedford** [comment]
Great, glad its making sense. Better docs on these workflows will be coming, just focusing on API stability here still.

**Comment by guybedford** [comment]
Just let me know if there is anything left to follow up on here in blanking out the override at all? Closing for now.
