### ISSUE TITLE
override for malihu custom scrollbar

### ISSUE THREAD

**Issue by Aaike** [jspm/registry#354]
Hi i submitted an override for this plugin which seemed to be working , but on closer inspection it doesn't work if jquery wasn't already included by another module.
I am testing now with this local override : 

```javascript
{
  "main": "jquery.mCustomScrollbar.js",
  "files": [
    "jquery.mCustomScrollbar.concat.min.js",
    "jquery.mCustomScrollbar.css",
    "jquery.mCustomScrollbar.js",
    "jquery.mCustomScrollbar.min.css",
    "mCSB_buttons.png"
  ],
  "registry": "jspm",
  "format": "global",
  "dependencies": {
    "jquery": "github:components/jquery"
  },
  "shim": {
    "jquery.mCustomScrollbar.js": {
      "deps": ["jquery"]
    },
    "jquery.mCustomScrollbar.concat.min.js": {
      "deps": ["jquery"]
    }
  }
}
```

and i get this Error :
```
Uncaught ReferenceError: jQuery is not defined
```
at [this line](https://github.com/malihu/malihu-custom-scrollbar-plugin/blob/master/jquery.mCustomScrollbar.js#L43)

must be doing something wrong ...
also you mentioned it is not advised anymore to use `files`, `directories` or `ignore` to filter files/directories, what would be the recommended way to to that then ?

**Comment by guybedford** [comment]
I think this might be because the shims need to be without the `.js` extension to work.

**Comment by Aaike** [comment]
omg... of course thank you
