### ISSUE TITLE
jQuery + Angular + Angular Modules results in broken App

### ISSUE THREAD

**Issue by nkoterba** [jspm/registry#358]
I've created a sample project to show the behavior here: https://github.com/nkoterba/jquery-breaks-angular-es6

I'm also going to post this issue with the AngularJs team since I'm not entirely sure why or what's causing the issue (is it Jquery's fault? Angular's fault? Babel's es6 transpiler? jspm?)

In summary, importing jquery breaks Angular's module include capability:

**Works** --> myApp *is* passed the 'ngMaterial' dependency during Angular startup
```javascript
import angular from 'angular';
import material from 'angular-material';
//import $ from 'jquery'; Works b/c jquery is commented out

angular.module('myApp', ['ngMaterial']);
```

**Breaks App** --> myApp is not passed the 'ngMaterial' dependency during Angular startup
```javascript
import angular from 'angular';
import material from 'angular-material';
import $ from 'jquery'; // Breaks app

angular.module('myApp', ['ngMaterial']);
```

I was able to get the application to *work* by installing jquery via jspm using an override and setting it's format to global:

```javascript
jspm install jquery -o "{format: 'global'}"
```

I got the inspiration to set jquery as global from this SO post: http://stackoverflow.com/a/29267477

Since I'm just learning jspm, I wanted to know if this is a common requirement needed when using jQuery via jspm or whether indeed this is some conflict between one of the many libraries/components involved.

**Comment by guybedford** [comment]
This is a timing issue and a common problem for users of Angular with SystemJS.

Basically you cannot use an `ng-app` in the HTML tag, and need to manually bootstrap your Angular app since dependencies are loaded asynchronously.

Adding jQuery just created enough delay to cause the default Angular bootstrap to happen before loading the app modules instead of after.

You want something like:

```javascript
System.import('app').then(function() {
  angular.bootstrap(); // I think it's this? or something like that.
});
```

**Comment by nkoterba** [comment]
Great info! Thanks.

Is `document.ready` event equivalent to `System.import().then` promise callback?  In other words, if the document is ready does that mean Systemjs has finished all its imports?

I ask because other examples I've seen of bootstrapping angular with systemjs use the document.ready callback instead of the System.import promise, e.g.:
```javascript
function bootstrap() {
	angular.element( document ).ready(
		() => angular.bootstrap( document, [ APP_NAME ], { strictDi : true })
	);
}
```

Wondering if those examples are wrong as well...

**Comment by guybedford** [comment]
In theory you should wait on both document.ready and the System.import to both complete.

In practise you can put your `System.import` call at the end of the HTML page, or at least after the relevant DOM elements and not need to wait on that. Typically the minor delay is enough for things to load anyway as long as you don't have script or link tags after the System.import script.

**Comment by nkoterba** [comment]
@guybedford In my application, we put the system.import at the very end of the page so I think that should help.  We'd prefer not to clutter up our main index.html page with angular/bootstrapping code so will see if we can somehow hook into the System.Import promise result within our bootstrap.js file.

Thanks for the help! I'm closing this issue since I've been able to resolve it.

```javascript
...
<script src="libs/system.js"></script>
<script src="config.js"></script>
<script>
		System.import('./bootstrap');
</script>

</body>
</html>
```

**Comment by simonh1000** [comment]
OMG - this is a huge gotcha. It would be great to add to the readme that Angular needs to be bootstrapped differently.

I've now tried to move to this style but end up with `TypeError: modules.unshift is not a function(…)`  in my console. Any suggestions

```
System.import('./wp-content/themes/af2015/assets/app/app')
.then(function() {
    angular.bootstrap(document, 'af2015App', { strictDi : true });
})
.catch(function(e) {
    console.error(e);
});
```

**Comment by simonh1000** [comment]
OMG - this a huge gotcha. Could it be added to the Readme? (I'm happy to provide PR)

**Comment by hogart** [comment]
Changing ng-app to angular.bootstrap is not much of a problem per se, but quoting angular docs:

> Note: Protractor based end-to-end tests cannot use this function to bootstrap manually. They must use ngApp.

What can be the solution if I want to have protractor tests?
