### ISSUE TITLE
npm:uri-template-lite

### ISSUE THREAD

**Issue by cbas** [jspm/registry#374]
I'm able to import this npm package as CJS (Node) and ES6 (Babel Node) but not with JSPM in the browser.

Minimal error case:
https://gist.github.com/cbas/ce8ca794b8a104c0f28d

The problem only happens with the named import style.
```js
// in es6.js ...
import {URI} from 'uri-template-lite' // URI = undefined
import URI from 'uri-template-lite' // URI = {URI: {...}}
```

Are named imports not supported by JSPM when the package is transpiled from cjs format? It works fine either way via `babel-node` which is why I am confused.

**Comment by guybedford** [comment]
This will work in the next version of SystemJS, see https://github.com/systemjs/systemjs/issues/334.

**Comment by guybedford** [comment]
This should now be working in jspm@0.16.0-beta. Just let me know if you have any further questions.

**Comment by cbas** [comment]
Thanks! :+1:
