### ISSUE TITLE
Question about github repo and name

### ISSUE THREAD

**Issue by marcog83** [jspm/registry#375]
Hi, I really love this project. 
Seeing how easy the workflow is, conviced me immediatly to start develop es6. Thanks.

I have a question about "naming". 
I can install my github repo  with
`jspm install github:marcog83/RoboJS`

but I don't understand how to say jspm to map github:marcog83/RoboJS to "robojs", the name of the project. 
At the moment I do it by hand In config.js file. 
Is there something I'm missing?

thanks 
marco

**Comment by guybedford** [comment]
@marcog83 glad to hear that! `jspm install robojs=github:marcog83/RoboJS` is how you can alias modules on install.

**Comment by marcog83** [comment]
Thanks for the answer
