### ISSUE TITLE
jspm its trying to find system.js.map in jspm_packages/dist while its in jspm_packages/

### ISSUE THREAD

**Issue by Quadramma** [jspm/registry#392]
/git/misitioba/jspm_packages/dist/system.js.map:1 GET http://localhost/git/misitioba/jspm_packages/dist/system.js.map 404 (Not Found)

**Comment by Quadramma** [comment]
I just manually copy files in there to solve the issue.

**Comment by guybedford** [comment]
Do you know why it was looking in `dist` here? Did you move the SystemJS source? It would help to understand what you think the reason might be and if there's something in the source map itself that can be fixed.
