### ISSUE TITLE
Support for Optional Dependencies

### ISSUE THREAD

**Issue by aphex** [jspm/registry#393]
I have no idea how this would be managed and I am a bit stuck trying to get this all working like I want so I think what I need is optional dependencies in the registry but maybe I am totally off and there is already a solution. 

Essentially some packages have dependencies listed that are not strict, for example ionic. 
https://github.com/jspm/registry/blob/master/package-overrides/github/driftyco/ionic-bower%401.0.0-rc.0.json

You can see there is a dependency on ionic.css but ionic also has all the SASS in its source. A lot of time users will want to import that SASS and change theme colors and regenerate a custom CSS file. I struggled for a while with how to accomplish this, my first though was to patch config.js like this

```javascript
"github:driftyco/ionic-bower@1.0.0/css/ionic.css!": "styles/app.css!"
```
This feels super dirty but essentially I am using the fact that ionic is forcing that file to load my own custom css file that has been precompiled. I don't like this.... 

Next I tried intercepting System.instantiate with my own custom function and inspecting every load for the CSS I knew i didn't want. Throwing it away when I found it and letting the others flow through, this was also gross but accomplished the goal. This does not work when bundling though so thats out of the question, probably to dirty anyway. 

So I ended up installing ionic with a override that is essentially a copy of the one in the register without the CSS entry. This worked fine but I worry about what happens after I check this into version control and attempt to install it on another machine. I imagine the custom override is not remembered and I will be stuck with the CSS filled version.

So thats my explanation :) I hope it makes some sense. If there is already a good way to deal with this please let me know, otherwise maybe we can look at how optional deps could be implemented without causing a bunch of headaches for people.

**Comment by aphex** [comment]
Actually it does appear that the override is saved in my package.json, hooray :) but I am still thinking it could be cool to somehow set thing to optional.

**Comment by guybedford** [comment]
By optional dependencies are you referring to having the CSS file being optional? This is very much on the roadmap.

Using an override as you have done does sound like the right solution here to me.

**Comment by aphex** [comment]
Yup CSS being optional. And the override is working well so far. Good to hear its on the roadmap.
