### ISSUE TITLE
textAngular

### ISSUE THREAD

**Issue by lookfirst** [jspm/registry#433]
https://github.com/fraywing/textAngular

This one is going to need a bunch of overrides. I'm sorry this isn't a PR, but this one seems a bit over my head to get working right...

The main issue is that this project has its own version of rangy that it is distributed with and I don't think it is compatible with the latest version of rangy.

Just `import`ing the files from the dist folder has some issues to with some message about 'anonymous module already defined'.

**Comment by guybedford** [comment]
I guess it's just shimming `dist/textAngular` to be dependent on its files?

Something like - 

```json
{
  "format": "global",
  "shim": {
    "dist/textAngular": {
      "deps": ["./textAngular.css!", "./textAngular-rangy", "./textAngular-sanitize"]
    }
  },
  "dependencies": {
    "css": "*"
  }
}
```

**Comment by lookfirst** [comment]
I'll close this... I ended up just going with redactor. I don't have the time to mess with crazy people (not you, the textAngular developer). =)
