### ISSUE TITLE
pixi.js

### ISSUE THREAD

**Issue by bekos** [jspm/registry#476]
When installing with `jspm install pixi.js`, the `package.json` file is missing.

When browser tries to load this, I get the following error is:
`Potentially unhandled rejection [3] Error loading "npm:pixi.js@3.0.7/package.json!github:systemjs/plugin-json@0.1.0" at http://localhost:9999/jspm_packages/npm/pixi.js@3.0.7/package.json
Error loading "npm:pixi.js@3.0.7/package.json!github:systemjs/plugin-json@0.1.0" from "main" at http://localhost:9999/main.js
Not Found: http://localhost:9999/jspm_packages/npm/pixi.js@3.0.7/package.json (WARNING: non-Error used)`

Any idea? Thx.

**Comment by guybedford** [comment]
Sure, I've added https://github.com/jspm/npm/commit/4f06729b9e9cdfc9febec71322b68838af573af5, which seems to fix the issue. Will post a release shortly.

**Comment by bekos** [comment]
Thanks.
