### ISSUE TITLE
Babel jsx plugin with hot reloading and React support

### ISSUE THREAD

**Issue by timbur** [jspm/registry#481]
Before I submit a pull request, I'm curious about the current state of `jsx` support within `jspm` and `systemjs`.  The current `jsx` plugin (i.e., installed via `jspm install jsx`) says [it's deprecated and to use Babel](https://github.com/floatdrop/plugin-jsx#plugin-jsx-), so does that mean a `jsx` plugin is no longer actually required in later combinations of `systemjs` and `babel`?  Because when I first began working on [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx), it was definitely required.

At any rate, [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx) is really straightforward.  It will attempt to use whatever `babelOptions` you've configured for `systemjs` and fallback to some defaults, `{stage: 0, optional: ['runtime']}`, when calling `babel.transform` for the translation.  It has only one dependency, [`babel-plugin-react-hot`](https://github.com/loggur/babel-plugin-react-hot), added to `babel.transform`'s `options.plugins`, which of course exists to support hot reloading of React components by default.  You can use [`systemjs-reload`](https://github.com/loggur/systemjs-reload) to reload modules and [`babel-plugin-react-hot`](https://github.com/loggur/babel-plugin-react-hot) will handle the React hot reloading portion of it for you.

Builds/bundles have not yet been tested with all of this, but in development, all of this seems to handle everything thrown at it.  Some logic also needs to be added to [`babel-plugin-react-hot`](https://github.com/loggur/babel-plugin-react-hot) to exclude the hot reload code from production builds.  Tests will probably also eventually be added to everything, but so far it's all pretty straightforward.  Maybe we'll find out that people have some interesting edge cases that require tests sooner rather than later.

**Comment by timbur** [comment]
I guess the two questions I'm trying to ask are 1) Does it make sense to add [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx) to the registry? and 2) Should it replace the current `jsx` plugin or should it have its own name, `babel-jsx`?

**Comment by Munter** [comment]
babel jsx transpiling comes out of the box now, so it probably doesn't make much sense to add the current plugin as-is. But the hot reloading feature is certainly interesting, and I assume the plugin will become a lot simpler if it only has to do that one thing

**Comment by timbur** [comment]
The hot reloading portions of it are separate modules, so now I guess the question is:  How easy would it be to incorporate said plugin(s) into the default jsx transformation process?  I imagine it would still be easiest to just use [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx), but perhaps it deserves a different name that better indicates the React component hot reload functionality.

I'll test a few things real quick and see how the reloading might fit into the default jsx transformation.  [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx) is probably basically the exact same as the default and not really worth the time, so a name change is probably the best route.

**Comment by timbur** [comment]
@Munter `systemjs` is still requesting `jsx.js` when I `import test from './test.jsx!'`.  Can you show me what you mean by this?
> babel jsx transpiling comes out of the box now

**Comment by guybedford** [comment]
I guess it may make more sense to have a `babel` plugin as opposed to a `babel-jsx` plugin. The plugin would do the same job as the internal transpiler within SystemJS (including JSX conversion), but would allow the flexibility of separating the module format (ESM / AMD / CJS / global) from the transpilation process, which is the way things are moving. That is, it offers an alternative workflow to the internal transpilation, which is under consideration for removal anyway - read https://github.com/systemjs/systemjs/issues/579 for more info on this.

**Comment by timbur** [comment]
What's the currently recommended way to load/transpile `jsx` files?  Is it basically what you outlined [here](https://github.com/systemjs/systemjs/issues/579#issuecomment-121061941)?  And can you provide an exact example so I can be sure?

**Comment by timbur** [comment]
Also, everything is already designed as separate packages, so maybe this makes the most sense:

1.  Replace the [current `jsx` entry](https://github.com/floatdrop/plugin-jsx) with [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx) for people who currently have that as part of their workflow and want an extremely easy way to support both `stage 0` functionality (decorators, etc.) with Babel and hot reloading for React components.

2.  For people who will adopt the latest method of loading/transpiling (assuming it will be as outlined [here](https://github.com/systemjs/systemjs/issues/579#issuecomment-121061941)), I suppose I can try to better advertise the [`babel-plugin-react-hot`](https://github.com/loggur/babel-plugin-react-hot) plugin so that they may pass it to `babelOptions.plugins`.

**Comment by guybedford** [comment]
The current way of loading JSX is simply to use:

```javascript
System.config({ transpiler: 'babel', meta: { 'app/*': { format: 'es6' } } })`
```

The reason I'm pushing for a Babel plugin is because it may end up one day that we remove the internal transpiler layer entirely and make everything plugins as I outlined in that post. I don't see an issue with hot reloading features being bundled in, as long as they still work for users without the hot reloading system in place. It's not so much code that it adds bulk to the final output.

**Comment by timbur** [comment]
> The current way of loading JSX

That example config didn't seem to work for me but this did:
```js
System.config({
  "packages": {
    ".": {
      "main": "src/main",
      "defaultExtension": "js"
    }
  }
});
```

Then...
```js
System.import('.');
```

I.e., the only way I could get it to transpile (and not look for `file.jsx.js`) was if it was within `packages`.  Not a problem at all though, really.

Incorporating [`babel-plugin-react-hot`](https://github.com/loggur/babel-plugin-react-hot) into the above config was then as easy as this:
```js
var hotPlugin = require('babel-plugin-react-hot');

System.config({
  "babelOptions": {
    "stage": 0,
    "optional": [
      "runtime"
    ],
    "plugins": [
      hotPlugin
    ]
  }
});
```

And then the [development tool](https://github.com/loggur/web-tedit) I'm working on uses [`systemjs-reload`](https://github.com/loggur/systemjs-reload) to reload modules/components upon changing them, and it all seems to work now without the need for [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx).  Plus, this should be a better system overall, the main reason being that it solves the issue where some people like to use `jsx` code within `js` files.  Thanks for the guidance!  :)

That said, I'd be glad to submit a PR if you (@guybedford) still want to replace the current (outdated) `jsx` plugin with [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx).  It probably also wouldn't hurt to add [`babel-plugin-react-hot`](https://github.com/loggur/babel-plugin-react-hot) to the registry and maybe add a quick example/some documentation for it, which I would also be glad to do, though I still need to add some logic to it (`if (__DEV__) { ... }` or whatever the jspm equivalent is) to remove it from production builds.  Last thing: [`systemjs-reload`](https://github.com/loggur/systemjs-reload) may also deserve a spot in the registry even though I cut so much code out of it earlier to ensure React components' props/state are preserved, and after another small change which should eliminate the need for `System.trace = true`, it probably won't even be a dozen lines long lol.

**Comment by timbur** [comment]
I'm going to close this.  Thanks for helping me figure out the best configuration.

Perhaps portions of this conversation can be referenced later on will help others.  :)
