### ISSUE TITLE
Main array support

### ISSUE THREAD

**Issue by nicklasb** [jspm/registry#511]
Hi, 
In the usual npm-style package.json, main can be an array. If there are two items, jpsm/systemjs loads both.
 
It seems like it also can be two item in the package overrride, however, it seems like it only uses the first item in the array.

Two items should generate two requires(item), but only one appears.

**Comment by guybedford** [comment]
`main` as an array isn't supported in Node's package.json. How does npm deal with them? I expect it will only read the first file?

**Comment by nicklasb** [comment]
Oh, sorry, you are right of course. 
It is bower.json that has that. And I have completely misunderstood how that works as well, it only loads one file per file type:
http://bower.io/docs/creating-packages/#main

Actually, I have just understood that this must be a pretty unusual case, and that the situation will be fixed in the next version. However, it means that the angular-schema-form registry item doesn't work without a client-side adjustment. I missed that, since I made the local adjustments.
Not sure if there is a big point in reverting the registry registration because of that, as it soon will be fixed.

Either way, I am closing this issue now.
