### ISSUE TITLE
How to Load Third Party Modules That Exports A Global Value?

### ISSUE THREAD

**Issue by f15gdsy** [jspm/registry#539]
Hi,
I have read the doc "Package Module Format" saying we can indicates options like es6, amd, cjs and global. I'm wondering where should I declare this option?
Thanks!

**Comment by guybedford** [comment]
When installing you can provide this option via the override flag:

```
  jspm install github:some/package -o "{format: 'cjs'}"
```

**Comment by f15gdsy** [comment]
Thanks! It works perfectly!
