### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by jdanyow** [jspm/registry#540]
Hi @guybedford , I'm working on https://github.com/twbs/bootstrap/pull/17270

In the PR discussion there's some concern about using `github:components/jquery` as opposed to something more official like `github:jquery/jquery` or `npm:jquery`.

I used `github:components/jquery` to be consistent with what's in the registry.json:  https://github.com/jspm/registry/commit/2289542ec060d50484b468acc805fb446e1e728a

Can you comment on why it's aliased in the registry this way?  My guess was it's a slimmer install, but wasn't sure.  Do you see any reason why we shouldn't add a package override for `npm:jquery` and alias `jquery` to `npm:jquery` in the registry.json?  (and of course send a PR to the jquery repo).

**Comment by guybedford** [comment]
Thanks @jdanyow I posted a comment there, just let me know if you have any further questions about this.

**Comment by Gheoan** [comment]
+1 for `jquery` alias to `npm:jquery`.

**Comment by guybedford** [comment]
I'm open to using `npm:jquery` as the main jquery source, if it works completely as expected. PRs welcome.

**Comment by Gheoan** [comment]
`github:components/jquery`, `npm:jquery` and `github:jquery/jquery@2.1.4` have the same `jquery.js` and `package.json` (except `npm:jquery` and `github:jquery/jquery` specify the `main` field which is a plus).
