### ISSUE TITLE
jspm install can't download packages from npm and github due to proxy settings

### ISSUE THREAD

**Issue by ultrasonicsoft** [jspm/registry#541]
I am trying to run simple angular 2 unit test application. I have cloned below git and following steps given in readme file.

https://github.com/matthewharwood/Hit-the-gym

I have setup proxy setting for npm and disabled strict-ssl setting for git. I have also exported environment variable for http_proxy and https_proxy.

When I run below command

npm install
it throws error for "jspm install" command as below:

    C:\angularjs20\unit-test1\Hit-the-gym>npm install
    npm WARN package.json @ No repository field.
    npm WARN optional dep failed, continuing fsevents@0.3.8
    |
    > phantomjs@1.9.18 install C:\angularjs20\unit-test1\Hit-the-gym\node_modules\p
    antomjs
    > node install.js

    Download already available at C:\Users\bchavan\AppData\Local\Temp\phantomjs\pha
    tomjs-1.9.8-windows.zip
    Extracting zip contents
    Removing C:\angularjs20\unit-test1\Hit-the-gym\node_modules\phantomjs\lib\phant
    m
    Copying extracted folder C:\Users\bchavan\AppData\Local\Temp\phantomjs\phantomj
    -1.9.8-windows.zip-extract-1440415812246\phantomjs-1.9.8-windows -> C:\angularj
    20\unit-test1\Hit-the-gym\node_modules\phantomjs\lib\phantom
    Writing location.js file
    Done. Phantomjs binary available at C:\angularjs20\unit-test1\Hit-the-gym\node_
    odules\phantomjs\lib\phantom\phantomjs.exe
    -
    > ws@0.4.32 install C:\angularjs20\unit-test1\Hit-the-gym\node_modules\karma\no
    e_modules\socket.io\node_modules\socket.io-client\node_modules\ws
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

    C:\angularjs20\unit-test1\Hit-the-gym\node_modules\karma\node_modules\socket.io
    node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gy
     (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
    dules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
    -
    > @ postinstall C:\angularjs20\unit-test1\Hit-the-gym
    > jspm install

         Looking up npm:jquery

    warn Error on lookup for npm:jquery, retrying (1).
         Error: unable to verify the first certificate
             at Error (native)
             at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
             at TLSSocket.emit (events.js:104:17)
             at TLSSocket._finishInit (_tls_wrap.js:460:8)

    warn Error on lookup for npm:jquery, retrying (2).
         Error: unable to verify the first certificate
             at Error (native)
             at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
             at TLSSocket.emit (events.js:104:17)
             at TLSSocket._finishInit (_tls_wrap.js:460:8)

    warn Error on lookup for npm:jquery, retrying (3).
         Error: unable to verify the first certificate
             at Error (native)
             at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
             at TLSSocket.emit (events.js:104:17)
             at TLSSocket._finishInit (_tls_wrap.js:460:8)

    warn Error on lookup for npm:jquery
         Error: unable to verify the first certificate
             at Error (native)
             at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
             at TLSSocket.emit (events.js:104:17)
             at TLSSocket._finishInit (_tls_wrap.js:460:8)

    err  Error looking up npm:jquery.

    warn Installation changes not saved.

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodej
    \\node_modules\\npm\\bin\\npm-cli.js" "install"
    npm ERR! node v0.12.2
    npm ERR! npm  v2.7.4
    npm ERR! code ELIFECYCLE
    npm ERR! @ postinstall: `jspm install`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the @ postinstall script 'jspm install'.
    npm ERR! This is most likely a problem with the  package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     jspm install
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\angularjs20\unit-test1\Hit-the-gym\npm-debug.log

Below is the package.json file content:

     {
         "jspm": {
           "directories": {},
           "dependencies": {
             "jquery": "npm:jquery@^2.1.4"
           },
           "devDependencies": {
             "traceur": "github:jmcriffey/bower-traceur@0.0.89",
             "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.89"
           }
         },
         "scripts": {
           "postinstall": "jspm install",
           "start": "live-server --open=client/index.html --port=9090 ./"
         },
         "devDependencies": {
           "jasmine-core": "^2.3.4",
           "jspm": "^0.15.6",
           "karma": "^0.12.35",
           "karma-chrome-launcher": "^0.1.12",
           "karma-coverage": "^0.3.1",
           "karma-jasmine": "^0.3.5",
           "karma-jspm": "^1.1.5",
           "karma-phantomjs-launcher": "^0.2.0",
           "phantomjs": "^1.9.17"
         }
    
 Could anybody please help me to solve this issue?

Any help very much appreciated!

Thanks!

**Comment by guybedford** [comment]
I must admit my proxy knowledge is limited here. Does https://github.com/jspm/jspm-cli/issues/980 sound like it would sort this out for you? What proxy settings do you have in your .npmrc file?

**Comment by ultrasonicsoft** [comment]
Below is content of my .npmrc file:

    registry=http://registry.npmjs.org/
    https-proxy=<my corporate proxy>
    proxy=<my corporate proxy>
    strict-ssl=false
    python=python2.7

**Comment by guybedford** [comment]
@ultrasonicsoft perhaps try editing `~/.jspm/config` and adding `strictSSL: false` to the base-level then? (as well as setting the PROXY environment variables for request).

**Comment by ultrasonicsoft** [comment]
I do have added but still no luck.

    {
      "defaultTranspiler": "traceur",
      "defaultRegistry": "jspm",
      "registries": {
        "github": {
          "timeouts": {
            "lookup": 60,
            "build": 120
          },
          "remote": "https://github.jspm.io",
          "auth": "dWx0cmFzb25pY3NvZnQ6QWRtaW4xMjMhJTQwJTIz",
          "maxRepoSize": 0,
          "handler": "jspm-github",
          "username": "ultrasonicsoft",
          "password": "Admin123!@#"
        },
        "npm": {
          "timeouts": {
            "lookup": 60,
            "build": 120
          },
          "handler": "jspm-npm",
          "remote": "https://npm.jspm.io"
        },
        "jspm": {
          "timeouts": {
            "lookup": 60,
            "build": 120
          },
          "handler": "jspm-registry",
          "remote": "https://registry.jspm.io"
        }
      },
      "strictSSL": false
    }

**Comment by ultrasonicsoft** [comment]
I have added this entry but still no luck.

    {
      "defaultTranspiler": "traceur",
      "defaultRegistry": "jspm",
      "registries": {
        "github": {
          "timeouts": {
            "lookup": 60,
            "build": 120
          },
          "remote": "https://github.jspm.io",
          "auth": "dWx0cmFzb25pY3NvZnQ6QWRtaW4xMjMhJTQwJTIz",
          "maxRepoSize": 0,
          "handler": "jspm-github",
          "username": "ultrasonicsoft",
          "password": "<mypassword>"
        },
        "npm": {
          "timeouts": {
            "lookup": 60,
            "build": 120
          },
          "handler": "jspm-npm",
          "remote": "https://npm.jspm.io"
        },
        "jspm": {
          "timeouts": {
            "lookup": 60,
            "build": 120
          },
          "handler": "jspm-registry",
          "remote": "https://registry.jspm.io"
        }
      },
      "strictSSL": false
    }

**Comment by guybedford** [comment]
@ultrasonicsoft make sure you're setting the proxy variables exactly as in https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables. To be safe it might even be worth trying directly:

```
  HTTPS_PROXY=... jspm install jquery
```

Note we always use HTTPS in jspm, so if it is an HTTP-only proxy that might be an issue as well.

**Comment by guybedford** [comment]
@ultrasonicsoft also note the auth token you shared above exposes your GitHub password publicly. You should change your GitHub password immediately.

**Comment by piggyslasher** [comment]
Our proxy is a http:// address. In my `.npmrc` file:
```
proxy=http://10.129.49.21:8080/
https-proxy=http://10.129.49.21:8080/     <--note - our https proxy points to http://. this works for npm, git and all the others.
strict-ssl=false
```
1. Tried adding `"strictSSL": false` to the `~/.jspm/config` and it didn't work.
2. Tried doing `HTTPS_PROXY=http://10.129.49.21:8080/ jspm install jade`.

**Comment by ultrasonicsoft** [comment]
I have solved this issue long back but forgot to close the issue.
Thanks all for your help.

**Comment by liuxihua** [comment]
@ultrasonicsoft ， i still have this problem , could you pls post your solution here ? thanks

**Comment by ultrasonicsoft** [comment]
@liuxihua I followed steps given below and it solved my issue:
https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

Issue was my password had special characters and they need to to be escaped using HTML encoding e.g. %20 etc. After encoding my password and following above steps, it solved my issue.

**Comment by brookemitchell** [comment]
I am in a similar position to @piggyslasher I believe, using an http:// https proxy
I am able to git clone, jspm install npm: packages, and run request in your example script:

`
var request = require('request');

request({
  uri: 'https://user:pass@github.com/jspm/jspm-cli',
  headers: {
    'User-Agent': 'jspm'
  },
  followRedirect: false,
  strictSSL: false
})
.on('response', function(res) {
  console.log(res.statusCode);
});
`

But I see the 
Error: unable to verify the first certicate error still

Any advice deeply appreciated.

**Comment by guybedford** [comment]
@brookemitchell `jspm install git:x` or `jspm install github:x`?

**Comment by brookemitchell** [comment]
Edit: Fixed when I disable NODE_TLS_REJECT_UNAUTHORIZED, [](https://www.npmjs.com/package/ssl-root-cas) so look like I need to generate a certificate.

Ah sorry jspm install github:x, jspm init -y fails to grab github:systemjs/systemjs with this error as well 
I also have `strictSSL: false` in the base of my .jspm/config
