### ISSUE TITLE
npm:cwise-compiler broken

### ISSUE THREAD

**Issue by neothemachine** [jspm/registry#554]
`System.import('npm:cwise-compiler')` loads the following:

```
https://npm.jspm.io/cwise-compiler@1.1.2/compiler.js -> 200
https://npm.jspm.io/cwise-compiler@1.1.2/lib/thunk -> 404
```

So, for some reason it doesn't append `.js` to the second import. I'm not sure at which level the error is here.

**Comment by guybedford** [comment]
`cwise-compiler@1.1.2` is working fine for me - make sure you are running the latest version of jspm and SystemJS, otherwise perhaps try `jspm install npm:cwise-compiler -f`.

**Comment by neothemachine** [comment]
I'm trying it via the CDN only, just run the import on the jspm.io web console and you can see the error.

**Comment by guybedford** [comment]
@neothemachine thanks so much - I forgot to enable `defaultJSExtensions: true` by default for the CDN SystemJS build to ensure this compatibility. It should be working now.
