### ISSUE TITLE
angular-cookies dependency causes 'Tried to load angular more than once' warning

### ISSUE THREAD

**Issue by glendaviesnz** [jspm/registry#558]
Hi

I just installed angular-cookies via jspm and when I include it with an
import 'angular-cookies';
running the app gives a "WARNING: Tried to load angular more than once."

if I comment out the following line at the top of angular-cookies.js then the warning disappears and everything works as expected.
"deps angular";

I have tried playing around with the deps settings in the packages jspm.json file instead but couldn't resolve the issue that way. Any thoughts on how to resolve this issue without having to edit the  angular-cookies.js gratefully received.

Glen

**Comment by guybedford** [comment]
The way to fix this is exactly to use overrides to ensure that there is only one version of Angular in the application. Override map configuration can be useful for this as well via `jspm install some-dep -o "{map:{angular:'my-angular-version'}}"`. It is a manual and careful process though, yes.

**Comment by glendaviesnz** [comment]
Perfect! Thanks for the hint, multiple versions of angular was in fact the issue, eg. in config.js was 

  map: {
    "angular": "npm:angular@1.4.5",
    "angular-cookies": "github:angular/bower-angular-cookies@1.4.5",

    "github:angular/bower-angular-cookies@1.4.5": {
      "angular": "github:angular/bower-angular@1.4.5"
    },

Changing this to 

  map: {
    "angular": "npm:angular@1.4.5",
    "angular-cookies": "github:angular/bower-angular-cookies@1.4.5",

    "github:angular/bower-angular-cookies@1.4.5": {
      "angular": "npm:angular@1.4.5"
    }

Fixes the issue. Will remember to use the override map next time when installing anything that has a dependency on angular.

Many thanks for all your hard work on jspm.
