### ISSUE TITLE
Website broken in Safari 9.0 [El Capitan]

### ISSUE THREAD

**Issue by chapati23** [jspm/registry#605]
getting a js-error in the console when trying to search for packages. guessing safari is not liking a certain character somewhere…

![screen shot 2015-10-07 at 15 30 59](https://cloud.githubusercontent.com/assets/117495/10338874/b02eaeb6-6d08-11e5-9f6c-dc081d871add.png)

**Comment by guybedford** [comment]
Thanks @chapati23 I'd suggest posting an issue to that project itself, as the call to `atob` is run within its own code, not jspm or SystemJS code.

**Comment by chapati23** [comment]
sorry, i looked around a bit but couldn't find it (also needs a proper url IMO).

what's the correct repo?

**Comment by guybedford** [comment]
It's at https://github.com/kasperlewau/registry/tree/gh-pages

**Comment by chapati23** [comment]
just tried. but apparently i can't post issues in there. no sufficient permissions?


On Oct 08, 2015, at 06:26 PM, Guy Bedford <notifications@github.com> wrote:

It's at https://github.com/kasperlewau/registry/tree/gh-pages

**Comment by guybedford** [comment]
//cc @kasperlewau it seems like the registry site uses `atob` on text that isn't restricted to the subset of allowed characters. There's a technique in https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding which may be useful here to enable Safari support for the site if you're still able to work on this.

**Comment by kasperlewau** [comment]
Hiya! 

> just tried. but apparently i **can't post issues** in there. no sufficient permissions?

Oh dear. I'll get on that right now. 

In terms of taking care of the issue itself, I'll do my best to have a look at it in the coming days but barring that - a PR would be most welcome. Thanks for letting me know!

**Comment by kasperlewau** [comment]
@chapati23 Issues are now enabled on my repo, and I took the liberty of creating it for you. 

https://github.com/kasperlewau/registry/issues/3

**Comment by chapati23** [comment]
great, thanks!

On Oct 12, 2015, at 08:41 PM, Kasper Lewau <notifications@github.com> wrote:

@chapati23 Issues are now enabled on my repo, and I took the liberty of creating it for you.
kasperlewau#3
