### ISSUE TITLE
jspm install pouchdb issue

### ISSUE THREAD

**Issue by stephenlautier** [jspm/registry#614]
Hi,

I'm trying to install the library `pouchdb` using `jspm install pouchdb`, however by doing so the dependencies are not being pulled + the `main` within pouchdb `package.json` is not pointing to the dist https://github.com/pouchdb/pouchdb/blob/master/package.json#L5 - and instead pointing to the source which requires dependencies to be defined https://github.com/pouchdb/pouchdb/blob/master/lib/index.js

I've also opened a ticket at their end thought pointing at the dist is the correct way, however it seems not
https://github.com/pouchdb/pouchdb/issues/4460

Can you kindly enlighten me?
- Is it something wrong with the definition of the libary e.g. `package.json`?
- Am I installing it wrong?

I've also tried to install it using `jspm install pouchdb=npm:pouchdb@5.0.0`, this way dependencies are being pulled however not configured automatically within the `map` and I get 404 errors.

Your help is much appreciated.

**Comment by guybedford** [comment]
@stephenlautier there's an override for pouchdb contained at https://github.com/jspm/registry/blob/master/package-overrides/github/pouchdb/pouchdb%403.0.6.json, which was added previously to make this work. A new major would likely need to have this override added again. It is worth considering if using the `npm:pouchdb` version is preferable too.

**Comment by stephenlautier** [comment]
I guess the best way rather than package overrides is to add it to their package instead as following:
```
{
  "main": "./lib/index.js",
  "jspm": {
    "main": "dist/pouchdb.js"
  }
}
```

As stated, for the `npm:pouchdb`, how would you go about dependencies? Since all their dependencies were giving 404's, I believe that is because it requires the maps within the config. Should you add them manually to the maps? 
Would it be best to list them as dependencies for JSPM, within their `package.json`?

Just want to understand which is the correct way to do it in order to help me and maybe other people. Thanks!

**Comment by guybedford** [comment]
I would suggest experimenting locally with the overrides to work out what works best here. If the dependencies are unnecessary then they can be removed via a `dependencies: {}` in the override. Once you have the right override, do post it as a PR to the registry here and ideally to pouchdb itself to support jspm. Just let me know if you need further help - and thanks for thinking about others here.

**Comment by stephenlautier** [comment]
Thanks for your time, I've contributed to the library itself to support JSPM via the `jspm` element within package.json.
