### ISSUE TITLE
JSPM pulls old dependencies for Angular 2 alpha 44

### ISSUE THREAD

**Issue by dsebastien** [jspm/registry#620]
Angular a44's original package.json file lists more recent dependencies versions than those pulled by `jspm install angular2`.

@guybedford: @robwormald had pushed a package override in the past (https://github.com/jspm/registry/blob/master/package-overrides/npm/angular2%402.0.0-alpha.27.json); may that override be responsible for the old dependencies being pulled? Or am I supposed to clean up some cache folder?

I'll submit a PR with a new package override just in case my assumption is correct..

**Comment by dsebastien** [comment]
(or maybe the solution is the opposite and is simply to remove the old override? :p)

**Comment by robwormald** [comment]
i reckon the solution here is remove the old one - if you update that PR to do so i'll merge it, and then we can see how it works. normally we'd probably not do this, but that was a suuuuper early alpha so i think its probably fine

**Comment by dsebastien** [comment]
Done!

In any case, the behavior of JSPM in this case is rather surprising to me. I wouldn't expect an override for a specific version to still apply for a newer ones. I guess it depends on what is being overridden...

**Comment by guybedford** [comment]
:+1:
