### ISSUE TITLE
jquery-ui 'amd' mode

### ISSUE THREAD

**Issue by aaronmars** [jspm/registry#629]
When installing jQueryUI via `jspm install jquery-ui`, a few of the amd modules under the ui/ directory are getting annotated with:
```javascript
"format global";
"deps jquery";
```
These are: `draggable.js`, `datepicker.js`, `sortable.js` and `widget.js`.
All of the other modules are getting `"format amd";` as expected.

This is causing issues when I'm trying to use them individually through something like:
```javascript
import draggable from 'jquery-ui/ui/draggable';
```
After bundling them with the jspm API, the error in the console is:
`Uncaught TypeError: base is not a function`

This all goes away after manually changing the `"format global"` to `"format amd"` (the `"deps jquery"` line seems to be innocuous, and doesn't really change anything, but it certainly seems to be added erroneously since it only appears in these problematic files).

After the manual changes, they can all be used inside an ES6 module by following the official jQUI documentation here: https://learn.jquery.com/jquery-ui/environments/amd/

This issue might be related to the fact that these 4 files are the only ones listed in https://github.com/jspm/registry/blob/master/package-overrides/github/components/jqueryui%401.11.3.json
Interestingly, the version that is loaded is 1.11.4, not 1.11.3, so I'm still a bit confused about what's going on here.

**Comment by guybedford** [comment]
Thanks, I've removed the shims in https://github.com/jspm/registry/commit/57cef69acd0da9ac864d620a450381e1b28a4041 which seems to resolve this. Overrides apply for all versions semver compatible with the override version.
