### ISSUE TITLE
angular-cookies is not exporting angular module name

### ISSUE THREAD

**Issue by Rush** [jspm/registry#641]
File `bower-angular-cookies@1.4.7.js` has:
```
module.exports = require("github:angular/bower-angular-cookies@1.4.7/angular-cookies");
```

While it should have something like `angular-messages` has:
```
module.exports = require("github:angular/bower-angular-messages@1.4.7/index");
```

Note, other modules like `angular-animate` have this problem as well.

**Comment by guybedford** [comment]
You can alter the main on install by using the `main` override - `jspm install github:angular/bower-angular-cookies -o "{main:'index.js'}"`.

**Comment by Rush** [comment]
Right, thanks for the fix, but can't we fix the root of the problem somehow?

**Comment by guybedford** [comment]
The reason for this is that the bower main (https://github.com/angular/bower-angular-cookies/blob/master/bower.json#L4) takes preference to the package.json main (https://github.com/angular/bower-angular-cookies/blob/master/package.json#L5).

**Comment by guybedford** [comment]
Sorry the reason is actually that the following override is applying here - https://github.com/jspm/registry/blob/master/package-overrides/github/angular/bower-angular-cookies%401.3.0-rc.1.json, which is setting the main. Usually the package.json main will be checked before the Bower main.
