### ISSUE TITLE
Are overrides version specific?

### ISSUE THREAD

**Issue by techniq** [jspm/registry#642]
When I went to install angular-ui-select using `jspm install angular-ui-select` it pulled down version 0.13.2 which didn't seem to have the package overrides as specified [here](https://github.com/jspm/registry/blob/master/package-overrides/github/angular-ui/ui-select%400.9.6.json).

If I explicitly installed version 0.9.6 using `jspm install angular-ui-select@0.9.6`, it used the overrides (primarily including the CSS file).

Is it possible to make an override not specific to a version (or a range)?

**Comment by guybedford** [comment]
Overrides apply to all versions semver compatible with the override. So an override for `0.9.6` will apply for all `0.9.x` greater than that version.

**Comment by techniq** [comment]
I see.  It seems the `angular-ui-select` one needs updated as the current version is `0.13.2` (and is the default version grabbed by jspm).  I guess the better thing would be to submit a PR to them to put the shim items into their `package.json` right?

**Comment by guybedford** [comment]
Yes it is best to have it maintained with the package itself, but feel free to submit a registry PR in the mean time if you like.
