### ISSUE TITLE
Overrides in packages are not enforced when defined in a dependency

### ISSUE THREAD

**Issue by niieani** [jspm/registry#645]
Here's my situation:
I've got this package: https://github.com/niieani/rethinkdb-websocket-client
For it to work it needs to override `npm:rethinkdb`'s imports for `net` and `tls`.
So, I've added the following to its package.json's `jspm` definition:
```json
    "overrides": {
      "npm:rethinkdb@2.1.1": {
        "map": {
          "net": "./dist/TcpPolyfill.js",
          "tls": "./dist/TlsStub.js"
        }
      }
    }
```

Now when I install the package in another project, via `jspm install github:niieani/rethinkdb-websocket-client`, the overrides are not respected, i.e. the `net` and `tls` packages that are `import`ed from `rethinkdb` that is imported by `rethinkdb-websocket-client` are not overriden as defined. Is this a bug, or am I doing something wrong?
In fact, the only way to make it work is to define the override again in the project that requires my `rethinkdb-websocket-client`, like this:
```json
    "overrides": {
      "npm:rethinkdb@2.1.1": {
        "map": {
          "net": "github:niieani/rethinkdb-websocket-client@0.4.8/dist/TcpPolyfill.js",
          "tls": "github:niieani/rethinkdb-websocket-client@0.4.8/dist/TlsStub.js"
        }
      }
    }
```
This would mean the overrides are not enforced when defined in a dependency.

**Comment by guybedford** [comment]
Yes, overrides do not apply transitively in this way. For more information on the issue see https://github.com/jspm/jspm-cli/issues/854.

**Comment by guybedford** [comment]
To resolve this, check the above overrides into the jspm registry here via a PR.

**Comment by niieani** [comment]
@guybedford The problem is the overrides are there to enable special functionality to the underlying package. There might be legitimate uses of the package without those overrides. Adding the overrides to the jspm registry would only solve the problem for those wanting to use the package in a manner similar to mine, while complicating things for others, who don't want the overrides. Hence my issue here.

**Comment by guybedford** [comment]
@niieani you could try adding this custom map in the config.js file instead. Custom map values are designed to be preserved despite subsequent install operations, but if you have any issues with it at all, just let me know. Such a workflow is the ideal focus for these kinds of use cases, where you then control this at the configuration level instead of with overrides, which are really designed to always be shared.

**Comment by niieani** [comment]
@guybedford I've tried using map, however I found that it is not enforced for the dependencies of dependencies (only for the first-level dependencies), and this is what I'm trying to achieve.

**Comment by guybedford** [comment]
Yes, map does need to be explicit for each dependency.
