### ISSUE TITLE
Importing angular-chart.js

### ISSUE THREAD

**Issue by LuckY1** [jspm/registry#653]
Hi there,

I have trouble getting the 'angular-chart.js' plugin to load into my app.
I install via `jspm install npm:angular-chart.js`
Then i include into app.js: `import ngChart from "angular-chart.js";`
The following error shows in console:

```
GET http://localhost:8080/Chart.js 403 (Forbidden)
Error: XHR error (403 Forbidden) loading http://localhost:8080/Chart.js
	Error loading http://localhost:8080/Chart.js as "Chart.js" from http://localhost:8080/jspm_packages/npm/angular-chart.js@0.8.5/dist/angular-chart.js
    at o (http://localhost:8080/jspm_packages/system.js:4:12597)
    at XMLHttpRequest.s.onreadystatechange (http://localhost:8080/jspm_packages/system.js:4:13122)
```

Here is the part in the config.js:

`"angular-chart.js": "npm:angular-chart.js@0.8.5",`

```
"npm:angular-chart.js@0.8.5": {
      "angular": "npm:angular@1.4.7",
      "chart.js": "npm:chart.js@1.0.2",
      "fs": "github:jspm/nodelibs-fs@0.1.2"
 },

"npm:chart.js@1.0.2": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
 },
```

It seems that the chart.js dependency isn't loaded properly.
Am I doing something wrong in general?

**Comment by guybedford** [comment]
It sounds like this might be a casing issue actually where in your map config you really want it to read:

```
"npm:angular-chart.js@0.8.5": {
      "angular": "npm:angular@1.4.7",
      "Chart.js": "npm:chart.js@1.0.2",
      "fs": "github:jspm/nodelibs-fs@0.1.2"
 },
```

Perhaps try manually changing it to the above and see if that helps?

**Comment by LuckY1** [comment]
OK, manually changing it did help. Will the change be persistent or will an update override it each time?

Thanks for the quick fix!

**Comment by guybedford** [comment]
You can submit an override with the following to the registry here:

```
"dependencies": {
    "angular": "^1.4.5",
    "Chart.js": "^1.0.2"
}
```

Or even send a PR to the original repo to have that updated as well.

**Comment by LuckY1** [comment]
This seems to be fixed in the newer versions of chart.js.
