### ISSUE TITLE
Update materialize override

### ISSUE THREAD

**Issue by guybedford** [jspm/registry#680]
The materialize override at https://github.com/jspm/registry/blob/master/package-overrides/github/Dogfalo/materialize@0.97.0.json uses dist paths, while the 0.97.3 version doesn't need the `dist` paths. A new 0.97.3 version can provide these changes but needs to be tested.

**Comment by alisabzevari** [comment]
I have created this override for 0.97.3 based on its [release package](https://github.com/Dogfalo/materialize/releases/download/v0.97.3/materialize-v0.97.3.zip) directory structure.

```json
{
  "main": "js/materialize",
  "shim": {
    "js/materialize": {
      "deps": [
        "jquery",
        "../css/materialize.css!"
      ],
      "exports": "$"
    }
  },
  "dependencies": {
    "jquery": "github:components/jquery",
    "css": "github:systemjs/plugin-css"
  }
}
```
and used this command to install:
`jspm install materialize=github:Dogfalo/materialize -o override.json`
The downloaded folder structure is different from the release zip contents.

Note that I am using jspm v0.16.18

**Comment by alisabzevari** [comment]
It seems that jspm downloads the [src release package](https://github.com/Dogfalo/materialize/releases/download/v0.97.3/materialize-src-v0.97.3.zip) instead of [built release](https://github.com/Dogfalo/materialize/releases/download/v0.97.3/materialize-v0.97.3.zip). How to tell jspm to use the second zip to download the package?

**Comment by guybedford** [comment]
Thanks! Can you send that as a PR here?

The rule in jspm is to use the first release archive. If we change the rule it will just break elsewhere!

In jspm 0.17 we're deprecating the handling of release archives to just always download the repo tarball, so we can avoid all these issues.

**Comment by alisabzevari** [comment]
As I said before, I couldn't make it work. The only working solution for me is to explicitly get the package from master branch:
```
jspm install materialize=github:Dogfalo/materialize@master -o override.json
```
I think we should provide a switch in the override json to tell jspm to not use the first release archive. If the switch did not exist in json, jspm can work based on the established convention (use the first archive).

**Comment by guybedford** [comment]
I'm not keen on introducing a flag behaviour on functionality that is being deprecated.

It should be possible to adjust the override to match the folder structure of the source archive file to get this to work.

**Comment by alisabzevari** [comment]
In the source archive file they have included sass files and compiled css doesn't exist in it!

**Comment by guybedford** [comment]
Ah I see. Ok I've published a `jspm-github` release that includes a fix for this in https://github.com/jspm/github/commit/18da66d2e002c80937a9c476dde019b7dd26d351.

Updating jspm should make this work then.

**Comment by alisabzevari** [comment]
Thanks. Sent a PR (https://github.com/jspm/registry/pull/686).

**Comment by guybedford** [comment]
:+1: much appreciated for your driving this.
