### ISSUE TITLE
Trouble setting up the correct overrides for github:T00rk/bootstrap-material-datetimepicker

### ISSUE THREAD

**Issue by jbgarr** [jspm/registry#687]
I can't figure out the correct override setup to use in order to properly install from github:T00rk/bootstrap-material-datetimepicker. I have read through the "Configuring-Packages-for-jspm" wiki docs, but still couldn't come up with an override setup that jspm was happy with. I think it would be nice to see additional docs regarding:
* how to handle the addition of multiple dependencies (an example of how to properly add an array of dependencies from the jspm CLI tool)
* how to handle adding dependencies that may come from different registries (a combo of one or more dependencies coming from npm and others coming from github)

I would appreciate any help you can provide regarding a proper override to get github:T00rk/bootstrap-material-datetimepicker installed successfully.

**Comment by jbgarr** [comment]
To add to this issue, I have added the following to my package.json's overrides section:
`"github:T00rk/bootstrap-material-datetimepicker@2.0.0": {
        "main": "js/bootstrap-material-datetimepicker",
        "dependencies": {
          "moment": "npm:moment@~2.10.2",
          "bootstrap": "github:twbs/bootstrap@^3.3.4",
          "jquery": "github:components/jquery@^2.1.4",
          "css": "github:systemjs/plugin-css@^0.1.11",
          "bootstrap-material-design": "github:FezVrasta/bootstrap-material-design@^0.5.7"
        }
      }`

Even with that override set up, I am getting an error saying that `moment` is not defined:
`Uncaught ReferenceError: moment is not defined(anonymous function) @ bootstrap-material-datetimepicker.js:1056J @ system.src.js:4703r.execute @ system.src.js:4703i @ system.src.js:4703n @ system.src.js:4703execute @ system.src.js:4703y @ system.src.js:4703w @ system.src.js:4703p @ system.src.js:4703h @ system.src.js:4703(anonymous function) @ system.src.js:4703run @ es6.promise.js:107(anonymous function) @ es6.promise.js:121flush @ $.microtask.js:25`

**Comment by guybedford** [comment]
The config you have done looks great. When setting the `dependencies` that will only inform jspm that it needs to download the depdencies. A shim is still necessary in order to say which files in the package depend on the dependencies, something like (in addition to the config properties you have):

```
  "shim": {
    "js/bootstrap-material-datetimepicker": ["moment", "bootstrap"]
  }
```

**Comment by jbgarr** [comment]
Thanks @guybedford. I was able to get the plugin to work correctly. In addition to the package.json overrides I included above, I also had to add a meta shim to my systemjs config.js file that includes the following:
```
"bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker": {
      "deps": ["bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css!"],
      "globals": {
        "jquery": "github:components/jquery@2.1.4",
        "moment": "npm:moment@2.10.6"
      }
    }
```

**Comment by guybedford** [comment]
Glad to hear that worked out.

Did you want to submit this configuration as an override?

It would basically look like:

package-overrides/github/repo/name@version.json:
```json
{
  "shim": {
    "js/bootstrap-material-datetimepicker": {
      "deps": ["bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css!", "jquery", "moment"]
    }
  }
}
```

If you'd like to submit that to the registry to help others it would be great, otherwise we can just leave it at that.

**Comment by jbgarr** [comment]
Ok, I've submitted a pull request for this configuration as an override.

**Comment by guybedford** [comment]
Many thanks!
