### ISSUE TITLE
Overrides being ignored, removed from package.json

### ISSUE THREAD

**Issue by jamiewinder** [jspm/registry#691]
I'm strugging to figure out what I'm doing wrong here. I want to install the 'toastr' plugin with JSPM, but the registry entry here specifies a dependency on 'github:components/jquery', but every other package I have uses 'npm:jquery'. I want to have them both using the same, which is straightforward to do in my config.js, but my override in my package.json file seems to disappear every time I install. This is what my overrides section looks like:

```javascript
    "overrides": {
      "github:CodeSeven/toastr@^2.1.2": {
        "main": "toastr",
        "format": "global",
        "dependencies": {
          "jquery": "npm:jquery@^2.1.4"
        },
        "files": ["toastr.js", "build"],
        "shim": {
          "toastr": {
            "deps": ["jquery", "./build/toastr.css!"],
            "exports": "toastr"
          }
        }
      }
    }
```

If I re-run `jspm install`, this section disappears and JSPM seems to use the original override on this repository. Am I doing something wrong, or does the JSPM registry always take precedence?

**Comment by guybedford** [comment]
The overrides section of the package.json uses exact version numbers (which in turn means for the semver range). Try:

```
    "overrides": {
      "github:CodeSeven/toastr@2.1.2": {
        "main": "toastr",
        "format": "global",
        "dependencies": {
          "jquery": "npm:jquery@^2.1.4"
        },
        "files": ["toastr.js", "build"],
        "shim": {
          "toastr": {
            "deps": ["jquery", "./build/toastr.css!"],
            "exports": "toastr"
          }
        }
      }
    }
```

**Comment by jamiewinder** [comment]
Yes. That was it, thanks.

**Comment by bhushanvaidya3** [comment]
This post helped me. Thanks @guybedford.
