### ISSUE TITLE
How does jspm deal with nested dependencies

### ISSUE THREAD

**Issue by chaudeco** [jspm/registry#702]
Here is the scenario:

**Module A** (deps):

  - underscore
  - backbone
  - backbone.marionette

**Module B** (deps):

  - **Module A**
  - bootstrap

**Final Project** (deps):

  - **Module A**
  - **Module B**
  - ...

----------

Module A config file is correct

Module B config file is correct

However, if I try to bundle my Final Project, jspm does not find underscore, backbone, ..., dependencies. I get an error like:

    Error: ENOENT, open '/Users/dev/final-project/underscore.js'
         at Error (native)

Jspm tries to get underscore in the Final Project's directory instead of Module A deps.

----------

**• What could I do to make nested dependencies work ? •**

**Comment by guybedford** [comment]
If ModuleA and ModuleB each have their own config file then they are separate jspm projects?

If so, then you can install one jspm project into another with `jspm link`.

The point is that only the package.json dependencies are read when installing a package (or linked project). The config file represents the version lock for the target project, which is private.

**Comment by chaudeco** [comment]
ModuleA and ModuleB are packages, they both have config file.

Even if I connect ModuleA and ModuleB in my Final Project, the problem remains the same:

ModuleA's mapping defined in ModuleA/config.js is not used in the Final Project. 
Jspm uses FinalProject/config.js instead of ModuleA/config.js in ModuleA's files (e.g. ModuleA/src/main.js).
So, If I install all ModuleA's deps in Final Project with the command line `jspm install xxx`, it will work because the mapping will be well described in FinalProject/config.js.
IMO, it's not a good way, ModuleA and ModuleB should be agnostic.

**Comment by guybedford** [comment]
@chaudeco `config.js` is not shared between packages. Only the package.json dependency ranges are used when installing one package into another. The `config.js` version lock is specific to my application instance, while the package.json defines my package version range.

**Comment by chaudeco** [comment]
@guybedford Ok, got it, tks.
