### ISSUE TITLE
Add package override for Bluebird to indicate it is a global module

### ISSUE THREAD

**Issue by drub0y** [jspm/registry#709]
Bluebird is a global module, but, because there's no package override for it and it comes from npm, JSPM's default logic is to treat it as a CommonJS module. This is a problem because one of the key scenarios for Bluebird right now is fixing [Edge's Promise performance problems](http://www.danyow.net/edge-promise-perf/) and that means including Bluebird _before_ SystemJS to establish the `Promise` type globally before SystemJS starts doing its work.

**Comment by guybedford** [comment]
Can you clarify exactly what the issue is currently? Is it that jspm is introducing its own wrappers to the file so it can't be included with a script tag?

If so, then we must be careful to just treat that one specific file as a global and not the whole repo. This can be done with a shim override of the form:

```json
{
  "shim": {
    "path/to/bluebird-browser-without-js-extension": true
  }
}
```

Let me know if something along those lines can work for you here.

**Comment by drub0y** [comment]
Hey @guybedford, sure let me explain. This is my first dip into the water with creating an override, so I appreciate any advice.

Bluebird is a polyfill for the Promise API. It is a single file only (at least in 3.1.1). The script is intended to be included via `<script>` tag and it adds or replaces the `window.Promise` global as well as the `window.P` global.

The specific use case is to actually deal with the fact that [Edge's Promise API implementation has some serious issues right now](http://www.danyow.net/edge-promise-perf/) that actually make SystemJS, which obviously makes heavy use of promises, perform terribly. So it needs to be included before SystemJS to replace that global Promise API before SystemJS starts doing its work.

**Comment by guybedford** [comment]
@drub0y you are completely right for the browser use case, but jspm does also work in Node (especially with the 0.17 release coming out that works comprehensively in Node for universal js as well).

When you load Bluebird in NodeJS, it does not get treated like a global but as CommonJS.

Bluebird has two versions - one for the browser and one for Node, and this is distinguished by the browser field in its package.json.

Your solution is exactly correct, but we just need to do it for the browser file only.

**I was just asking if you could test out the following override for me:**

```
  jspm install npm:bluebird -o "{ shim: { "js/browser/bluebird": true } }"
```

and let me know if that works ok for you? If so lets get this fix into the registry.

**Comment by drub0y** [comment]
@guybedford Ah, I understand 100% now. Chalk that up to y lack of experience, I was totally browser focused. Ok, I'll make the change and update the PR!

**Comment by drub0y** [comment]
So two questions:

 1. Should I add the following so that it _only_ ever pulls down the `js/browser` files:

```
  "directories":
  {
      "lib": "js/browser"
  }
```

 2. Since there's a `min.js` as well, I assume I also need to add a shim entry for that? Without it JSPM was still treating the `min.js` as a CommonJS module.

Let me know when you can and I'll either adjust based on your recommends or will commit like this and push/update the PR.

**Comment by guybedford** [comment]
@drub0y glad it is making sense now. (1) jspm works in the browser and Node, so we do want all the files. (2) generally we don't advise using the minified files in jspm as it provides a worse debugging experience even with source maps working, so I generally don't even encourage shimming them at all to rather have this as a production optimization only.

**Comment by drub0y** [comment]
@guybedford Ok, I updated the PR.

While I totally understand what you're saying about the minified file, I went ahead and shimmed it anyway because I honestly think a lot of people are really just going to want to include the `.min.js` and forget about it. I don't see any negative side effect from doing this, it only enables/simplifies another scenario. If people want to use the non-minified version and take care of combining/minifying themselves they still totally can. 

That said, if I'm missing something with this approach and this does somehow have a negative impact that I'm not aware of given my relative "newb" status with JSPM, please educate me further and I'll gladly fix.
