### ISSUE TITLE
depending on a repository directly from GitHub

### ISSUE THREAD

**Issue by alexisargyris** [jspm/registry#723]
Hello,

I am trying to install [github-api](https://github.com/michael/github) which depends on [axios](https://github.com/mzabriskie/axios) like this:

````
"dependencies": {
    "axios": "https://github.com/github-tools/axios.git",
    "base-64": "^0.1.0",
    "es6-promise": "^3.0.2",
    "utf8": "^2.1.1"
  }
````
I try this
````
jspm install npm:github-api
````
and I get back this
````
Downloading npm:github-api@0.11.2

warn Error on processPackageConfig
     npm dependency format https://github.com/github-tools/axios.git not currently supported by jspm. Post an issue if required.

warn Error processing package config for npm:github-api.

err  Error processing package config for npm:github-api.
````
Is there any way around this situation? Should I try using [jspm-git](https://www.npmjs.com/package/jspm-git)?

Thanks in advance

**Comment by guybedford** [comment]
Thanks, I've added a fix for this in https://github.com/jspm/npm/commit/6d85e725040493d7c2fd82c6d04a5648750205b2 pending release.

**Comment by alexisargyris** [comment]
You are great! Thanks!
