### ISSUE TITLE
How to download the complete package not just compiled version. ( Bootstrap ).

### ISSUE THREAD

**Issue by DavidStrada** [jspm/registry#743]
Hi guybedford, 

I'm trying to download the complete package ( bootstrap ) e.g. if i do `npm install bootstrap@v4.0.0-alpha.2 --save` i get `scss` files, `js` ... without them being compiled ( dist directorectory ). However when i do `jspm install npm:bootstrap@4.0.0-alpha.2` i only get .css and .js file and that's it, any thoughts ?

thanks,
David

**Comment by guybedford** [comment]
jspm 0.16 downloads GitHub release archives when present instead of the direct git tag. In jspm 0.17 we always use the git tag file structure. The other thing to check here is the registry entries to see if any `files` or `ignore` properties are present.
