### ISSUE TITLE
Angular-moment package installation help

### ISSUE THREAD

**Issue by mradamh** [jspm/registry#754]
Hi, I would love some help getting [angular-moment](https://github.com/urish/angular-moment) installed properly if anyone is willing.

I'm running `jspm install npm:angular-moment@0.10.3`

In`package.json` that begets `"angular-moment": "npm:angular-moment@0.10.3",` in the jspm dependencies.

In my config.js `map` section:

```
"angular-moment": "npm:angular-moment@0.10.3",
...
"npm:angular-moment@0.10.3": {
  "moment": "npm:moment@2.10.6",
  "process": "github:jspm/nodelibs-process@0.1.2"
},
```

When I `import 'angular-moment'` in my app and run I get the following:
![image](https://cloud.githubusercontent.com/assets/2448413/13012290/7c92c8ce-d15f-11e5-897a-d6351968f902.png)

I think I just don't understand the documentation on overrides/shims/etc for how to shim angular into the angular-moment package. I've tried various combinations, but haven't been able to get anything to work.

I can _manually_ set it in the map of config.js like so:

```
"npm:angular-moment@0.10.3": {
  "angular": "npm:angular@1.4.9",
  "moment": "npm:moment@2.10.6",
  "process": "github:jspm/nodelibs-process@0.1.2"
},
```

That works great, but of course gets overriden on subsequent `jsmp install`s.  

Pointers in the right direction would be super appreciated.

**Comment by guybedford** [comment]
It may help to look at an example override here, something like https://github.com/jspm/registry/blob/master/package-overrides/github/angular-ui/bootstrap-bower%400.12.0.json.

If you make a similar JSON file for angular-moment, you can use that with `jspm install npm:angular-moment -o custom-override.json`.

**Comment by mradamh** [comment]
Thanks you for the help!  i was able to figure out a shim config that worked.
