### ISSUE TITLE
Unable to reference github:blueimp/jQuery-File-Upload/js/jquery.fileupload-angular

### ISSUE THREAD

**Issue by martinsson** [jspm/registry#760]
New to jspm I'm blocking on how to reference this particular file from this repo.

I've tried for instance 
`jspm install jquery-file-upload -f -o "{main: 'js/jquery.fileupload-angular'}"
`
But I get a warning message and the right file is not downloaded
```
warn Main entry point not found for github:blueimp/jQuery-File-Upload@9.11.2.
Adjust this property in the package.json or with an override, setting "main": false if this is the intention.

```

On Gitter @geybedford told me 

> I think there's an existing override in the registry for this? Post a registry issue to track support if you like

I would have thought that would be here https://github.com/jspm/registry/tree/master/package-overrides/github 
but I can't find anything.

Anyone understands a bit more than me?

**Comment by guybedford** [comment]
There's already an override at https://github.com/jspm/registry/blob/master/package-overrides/github/blueimp/jQuery-File-Upload%409.3.0.json. So the `files` property in that override will cause all other files in the repo to be ignored except for that one. You can remove the files property with an override to revert - `jspm install jquery-file-upload -o "{files:null}"` should work I think.

**Comment by martinsson** [comment]
It did work. Thanks
