### ISSUE TITLE
jquery-ui source seems duplicated

### ISSUE THREAD

**Issue by nicolashemonic** [jspm/registry#773]
Hi,

When installing jQuery-UI from `jspm install jquery-ui` the source seems duplicated, for example:
jspm_packages\github\components\jqueryui@1.11.4\jquery-ui.js

also present in **ui** folder:
jspm_packages\github\components\jqueryui@1.11.4\ui\jquery-ui.js

finally Amd files are accessible in **ui\ui** folder:
jspm_packages\github\components\jqueryui@1.11.4\ui\ui\datepicker.js

So, when i import Amd modules the name seems strange:
`import "jquery-ui/ui/ui/datepicker"`

Thank you!

**Comment by guybedford** [comment]
That's really odd. I haven't got a nested `ui` folder at all myself. Have you tried `jspm install jquery-ui -f`?

**Comment by nicolashemonic** [comment]
`--force` option fixed issue! As usual, thank you Guy.
