### ISSUE TITLE
Create an override with dependencies and map config

### ISSUE THREAD

**Issue by nicolashemonic** [jspm/registry#774]
Hello,

Find below the package override for https://github.com/gvas/knockout-jqueryui

```js
{ 
    main: false, 
    dependencies: { 
        'knockout': 'github:knockout/knockout', 
        'jquery-ui': 'github:components/jqueryui'
    }, 
    map: { 
        'jquery-ui': 'jquery-ui/ui' 
    }
}
```

Override take successfully the dist folder with amd source and fetch knockout dependency.

However when "jquery-ui" is mapped to "jquery-ui/ui", the dependency (jquery-ui) is not fetched but module name in amd source are correctly replaced by "jquery-ui/ui".

How to specified the jquery-ui dependency and map jquery-ui path in knockout-jqueryui ?

Thank you!

**Comment by guybedford** [comment]
You can use a directories.dist override -

```
{ 
    main: false, 
    directories: {
      dist: 'ui'
    },
    dependencies: { 
        'knockout': 'github:knockout/knockout', 
        'jquery-ui': 'github:components/jqueryui'
  }
}
```

**Comment by nicolashemonic** [comment]
Thanks @guybedford , unfortunately that doesn't work, i can be misspoke...

- i want to use dist folder to fetch amd modules, that's okay
- knockout-jqueryui loads jquery-ui modules from 'jquery-ui/datepicker' (for example)
- i have set github:components/jqueryui dependency that provide modules from 'jquery-ui/ui/datepicker'

How configure knockout-jqueryui override to load jquery-ui modules from ui folder ?

**Comment by guybedford** [comment]
@nicolashemonic you can do these kinds of adjustments with map config - https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#map-configuration.

**Comment by nicolashemonic** [comment]
Yep i think i need map config but as i explained map config oddly works with dependency...

This override works correctly :
```js
{ 
    main: false, 
    dependencies: { 
        'knockout': 'github:knockout/knockout', 
        'jquery-ui': 'github:components/jqueryui'
    },
}
```

But when i add a map config to replace 'jquery-ui' by 'jquery-ui/ui' in knockout-jquery:
```js
    [...]
    map: { 
        'jquery-ui': 'jquery-ui/ui' 
    }
```

The map works but github:components/jqueryui is not downloaded...

It is a bug or a wrong override config between dependencies and map ?

**Comment by guybedford** [comment]
The workaround would be to do `map: { 'jquery-ui': 'jqueryui/ui' }, dependencies: { 'jqueryui': 'github:components/jqueryui' }`.

The reason for this is that it was convenient to be able to map dependencies to something local, and then not need to override all dependencies just to indicate that the dependency shouldn't be installed any longer.

We should really do this "skip install" thing if the dependency name has a custom map AND none of the local maps resolve to the dependency name. I've created https://github.com/jspm/jspm-cli/issues/1562 to track.

**Comment by nicolashemonic** [comment]
It works!

Thank you for your quick responses and these interesting explanations.
I am now able to pull-request an override for this package :)
