### ISSUE TITLE
Selectize.js

### ISSUE THREAD

**Issue by nlwillia** [jspm/registry#788]
I'm having trouble configuring (hacking) Selectize.js for use with JSPM 0.16.30.

There's a [registry entry](https://github.com/jspm/registry/blob/master/package-overrides/github/brianreavis/selectize.js@0.12.0.json) for it, but it's old.  The project has since moved to [selectize/selectize.js](https://github.com/selectize/selectize.js).  So just `jspm install selectize` isn't what I want.  That version also installs jquery as a dependency, and for the page I'm installing into there's already a jquery, so I want to be able to omit the selectize dependency and use the ambient one.

I tried `jspm install npm:selectize`, but got an error.
```
err  Error locating github:voodootikigod/node-csv/tarball/master.
```

So I'm working with `jspm install selectize=github:selectize/selectize.js` and trying to use override configuration in my package.json to pluck the parts that I want.  There's a `dist/js/standalone/selectize.min.js` in AMD format that includes selectize and its sifter and microplugin dependencies.  There's also a `dist/css/selectize.css` that I want to pull in with the CSS plugin.

```
  "overrides": {
    "github:selectize/selectize.js@0.12.1": {
      "main": "dist/js/standalone/selectize",
      "format": "amd",
      ...
    }
  }
```

I've tried various things with map and shim trying to make this work, but I'm not having much luck.  Ultimately, I'm dealing with a js file with the following AMD declarations:

```
define('sifter', factory);
...
define('microplugin', factory);
...
define('selectize', ['jquery','sifter','microplugin'], factory);
```

Sifter and microplugin are both embedded and not used anywhere else.  I'm assuming that JSPM will just accept them as AMD defines and provide them to the selectize declaration later.  `jquery` on the other hand is not defined, and I don't want it to be other than to inject `$` which is already globally available.

Is there a  way to make this work?  I can always pull these dependencies out into the main page, but then I lose the benefit of JSPM being able to bundle everything for production.

**Comment by guybedford** [comment]
Even though you have your own version of jquery, the plugin still needs to reference jquery itself as a dependency and as a shim for it to work. Perhaps try `jspm install selectivize -o "{dependencies:{jquery:'*'}}"` to ensure it only uses one version of jquery.

**Comment by nlwillia** [comment]
There is no jquery at all in my jspm project, so "\*" gets interpreted as `jspm:jquery@*`.  I'm not sure what to do with the other dependencies either since they are bundled but not known or used externally.  Yet the AMD requires in the main file still have to resolve somehow.
```
jspm install selectize=github:selectize/selectize.js -o "{ main: 'dist/js/standalone/selectize', format: 'amd', shim: { 'dist/js/standalone/selectize': { deps: ['jquery', 'sifter', 'microplugin', '../../css/selectize.css!'] } }, dependencies: { 'jquery':'*', 'sifter':'*', 'microplugin':'*' } }"
```
```
{
  "devDependencies": {
    "jspm": "^0.16.30"
  },
  "jspm": {
    "dependencies": {
      "selectize": "github:selectize/selectize.js@^0.12.1"
    },
    "devDependencies": {},
    "overrides": {
      "github:selectize/selectize.js@0.12.1": {
        "main": "dist/js/standalone/selectize",
        "format": "amd",
        "shim": {
          "dist/js/standalone/selectize": {
            "deps": [
              "jquery",
              "sifter",
              "microplugin",
              "../../css/selectize.css!"
            ]
          }
        },
        "dependencies": {
          "jquery": "jspm:jquery@*",
          "sifter": "jspm:sifter@*",
          "microplugin": "jspm:microplugin@*"
        }
      }
    }
  }
}
```
If I don't declare the shim `deps` then they never get loaded even though they're all bundled together in the main file.  But the "\*" dependency resolutions end up pulling in external files instead of the files that are [bundled](https://github.com/selectize/selectize.js/blob/master/dist/js/selectize.js) or the ambient jquery.

So there are a couple of questions here...the original "how do I wire in an ambient global under a local AMD name" as well as "how do I ensure that local, bundled AMD defines are visible within the same module".

**Comment by guybedford** [comment]
Which ambient files do you mean? It seems like it would attempt to import sifter and microplugin from https://github.com/selectize/selectize.js/blob/master/dist/js/selectize.js#L22, both of which you have installed?

If you have a global jQuery and want to make it available, you can either point SystemJS to the global jQuery CDN source or whatever it is so that SystemJS loads it. Or if you really want to use the exising global, you can assign it to a module with a small local wrapper module like:

jquery.js
module.exports = $;

And then updating all jquery references in your config to reference that file. Although local file maps for dependencies are only supported in jspm 0.17.

**Comment by nlwillia** [comment]
Thanks for your suggestions on this.

I think what I need to do is just configure it as a global.  It's doing sort of a UMD thing where it tries AMD or CommonJS if available, but there's a global fallback that appears to have the no-frills, no-external-resolution behavior that I'm looking for, albeit a the expense of polluting the global namespace.

```
jspm install selectize=github:selectize/selectize.js -o "{ main: 'dist/js/standalone/selectize', format: 'global', shim: { 'dist/js/standalone/selectize': { deps: ['../../css/selectize.css!'], exports: 'Selectize' } } }"
```
```
{
  "devDependencies": {
    "jspm": "^0.16.30"
  },
  "jspm": {
    "dependencies": {
      "css": "github:systemjs/plugin-css@^0.1.20",
      "selectize": "github:selectize/selectize.js@^0.12.1"
    },
    "devDependencies": {
      "clean-css": "npm:clean-css@^3.4.10"
    },
    "overrides": {
      "github:selectize/selectize.js@0.12.1": {
        "main": "dist/js/standalone/selectize",
        "format": "global",
        "shim": {
          "dist/js/standalone/selectize": {
            "deps": [
              "../../css/selectize.css!"
            ],
            "exports": "Selectize"
          }
        }
      }
    }
  }
}
```

What I've been trying to do is think of the built module as an isolated context that, like an ES6 module, gets names injected and exports something, except I want to control that boundary by being able to insert things from global or elsewhere and insert code to manipulate what comes out, preferably without having to create literal wrapper modules in my project.  Internally, if it's declared as AMD, I want JSPM to wrap it in the machinery for AMD, but instead of doing full SystemJS resolution just operate in a locally isolated way with simple names that are locally bound instead of trying to pull in outside resources.  Maybe this is a weird use case or too different from what JSPM wants to be to consider.  Regardless, globals work even if they aren't ideal.
