### ISSUE TITLE
Purpose of '.jspm-hash' file?

### ISSUE THREAD

**Issue by tylerferguson** [jspm/registry#789]
Hello,

I've been playing around with jspm lately trying to get a feel for what it is up to behind the scenes. 
This .jspm-hash file that you get when you install a package is upsetting me a little because I cannot work out its exact role!

Is there any documentation for it? Or are you able to quickly explain what it does?

I figure it is used somewhere along the way to identify packages (possibly in the registry?), but where? Is that even correct?

Thanks,

Tyler

**Comment by guybedford** [comment]
This is the package hash, which jspm uses to evaluate if the package is freshly downloaded or needs to be downloaded again.

**Comment by tylerferguson** [comment]
Thanks for the response! Are you able to tell me how it's constructed?

I can see the first portion is the commit hash that matches the version of the package being used. Where does the rest come from?

**Comment by guybedford** [comment]
Sure, it's generated at https://github.com/jspm/jspm-cli/blob/master/lib/package.js#L511. Are you writing some sort of tooling on top of the workflow here? Closing, but feel free to continue discussion.

**Comment by tylerferguson** [comment]
Excellent. Thanks for that. 

No I'm not writing anything. I am currently in the middle of a blog post about using jspm as a client side package manager and thought I would take a look at the differences in a package installed with jspm vs. installing with bower. 

I felt I had gripped what everything was up to except the .jspm-hash so thanks for clearing that up.

**Comment by nlwillia** [comment]
@tylerferguson I'd be interested in reading that if you don't mind posting the link here once it's up.  Thanks.

**Comment by guybedford** [comment]
Sure, sounds great, just let me know if you have any further questions at all. I'd also strongly suggest looking into the jspm 0.17 version as well if you can which doesn't do any package code modifications, and has a much nicer handling of packages via separating the configuration into a separate package configuration file.

**Comment by tylerferguson** [comment]
Blog is up and running now @nlwillia . Thanks for your help @guybedford .

http://blog.scottlogic.com/2016/03/03/modularizing-client-side-dependencies-with-jspm.html
