### ISSUE TITLE
superagent stopped working

### ISSUE THREAD

**Issue by perrin4869** [jspm/registry#796]
Just tried installing superagent and it fails to import. I made a simple demo which I am hosting here: http://julian.dotcore.co.il/
Also, made a simple repo you can get here: https://github.com/perrin4869/jspm_superagent
Install simply using `jspm install`

**Comment by guybedford** [comment]
Try using jspm 0.17 here rather.

**Comment by perrin4869** [comment]
I see, `jspm@0.17beta9` indeed worked :)
I guess I'll update before the stable release then.
Btw, the automatic upgrade didn't work. I did `npm install jspm@beta && jspm init`, used the default settings, changed the html script tags to use `jspm.browser.js` and `jspm.config.js`, but when trying to load `index.html` it couldn't find babel. Not very critical though.
I don't wanna be pushy, but is there an estimate when 0.17 stable will be released? Thanks!

**Comment by guybedford** [comment]
@perrin4869 if you could share your upgrade case that would help a lot to test here. The beta can be considered stable to use :)

**Comment by perrin4869** [comment]
sure, I prepared a demo, will open an issue in jspm-cli!
