### ISSUE TITLE
trying to install greensock

### ISSUE THREAD

**Issue by Cortrah** [jspm/registry#805]
Hi all,

Trying to configure greensock without luck. Any help would be appreciated
The command I'm using to install it is from the registry and looks to be correct on git
'jspm install github:greensock/GreenSock-JS'

When I do this I can see the package installed in 
jspm_packages/github/greensock/Greensock-JS@1.18.2

in package.json I have
jspm: { 
  dependencies {
      "greensock": "github:greensock/GreenSock-JS@^1.18.2",

and in my js file i have
import 'greensock';
which was my first guess at the syntax
but have also tried other variations without luck

When I try to load the file I get
"Cannot GET /jspm_packages/github/greensock/GreenSock-JS@1.18.2.js"

I don't think it's a server configuration issue as other jspm modules are working fine, but that somehow I'm either installing or declaring it wrong, but any advice would be appreciated. 

Thanks!

**Comment by guybedford** [comment]
This is actually working fine when I try it. Make sure you're running the latest version of jspm - 0.16.30. Then perhaps try installing with a forced cache clear - `jspm install github:greensock/GreenSock-JS -f`.

**Comment by Cortrah** [comment]
Ok thanks for checking that I have the commands right, I just did the getting started steps with a repository from scratch and its giving me a 404 on system.js and config.js which makes no sense.

I think you can assume that this has something to do with my server now.
