### ISSUE TITLE
fixing the shim for angular-ui-select actually breaks

### ISSUE THREAD

**Issue by hikirsch** [jspm/registry#810]
because of https://github.com/jspm/registry/commit/af4d977104deb0eb4aabbdb5392a48f08175a543, we are now receiving this error when we compile, 

manually installing this package without any shims like so fixes the problem for us `jspm install angular-ui-select -o "{ shim: {} }"`

```
[09:48:44] Using gulpfile ~/Development/my-project/gulpfile.js
[09:48:44] Starting 'jspm'...
Unhandled rejection Error: CSS Plugin:
Broken @import declaration of "jspm_packages/github/angular-ui/ui-select@0.14.9/dist/dist/select.css"
    at file:///Users/adam/Development/my-project/src/main/resources/public/static/jspm_packages/github/systemjs/plugin-css@0.1.20/css-builder.js:76:13
```

**Comment by hikirsch** [comment]
meant to say, notice the double /dist

**Comment by guybedford** [comment]
Thanks, I've pushed a fix in https://github.com/jspm/registry/commit/04b5816ea9a3bd71b16340f5dc9136bef1027765.
