### ISSUE TITLE
Masonry override missing dependencies

### ISSUE THREAD

**Issue by MeirionHughes** [jspm/registry#828]
Currently the [override for desandro/masonry](https://github.com/jspm/registry/blob/master/package-overrides/github/desandro/masonry%403.1.4.json) doesn't specify that it has dependencies on 'outlayer' and 'get-size'. Bundling fails trying to resolve 'outlayer'. 

If I override with one of the distribution files... 
```
 "github:desandro/masonry@4.0.0": {
        "main": "dist/masonry.pkgd"
      },
```
...it gets past bundling. Given someone else added this override to registry I don't want to start changing it without authoritative opinion. 

```
import Masonry from 'masonry';
``` 
also works nicely with `"main": "dist/masonry.pkgd"` set

**Comment by guybedford** [comment]
Please do send a PR here if you can, working code wins!

**Comment by MeirionHughes** [comment]
Okay done. #830. Although I've added it for latest version, hopefully it won't break for whomever originally added for version 3.
