### ISSUE TITLE
esprima package override

### ISSUE THREAD

**Issue by hmalphettes** [jspm/registry#839]
Hi everyone, we are currently looking at making `jspm install esprima` behave better: not install the nodejs schims for the `fs` and `process` modules.

It seems we might end-up adding a package override here.

Your expert input would be much appreciated if in fact the best solution is to change esprima's package.json:
https://github.com/jquery/esprima/issues/1486#issuecomment-200919022

Let me know if we are better off with a package override here.

Thanks for your attention!

**Comment by ariya** [comment]
Note that as a library, Esprima does not depend on any modules (i.e. it is self contained).
However, included in its package is a command-line tool that relies on `fs` and `process`.

**Comment by guybedford** [comment]
As posted, a `jspmNodeConversion: false` override will likely be what is wanted here in the registry.

**Comment by hmalphettes** [comment]
OK, noted.
