### ISSUE TITLE
"aurelia-notification" has duplicate entry

### ISSUE THREAD

**Issue by eriklieben** [jspm/registry#842]
Hi,

My editor told me there is a duplicate entry in registry.json.
Not sure if this is an issue.

line 115: "aurelia-notification":"github:spoonx/aurelia-notification",
line 149: "aurelia-notification": "github:MarcScheib/aurelia-notification",

Gr, 

Erik

**Comment by guybedford** [comment]
Sure, which should be removed here do you think?

**Comment by eriklieben** [comment]
Not sure, don't know what the community would expect when installing aurelia-notification. 
***
If we only look at the cleanup of the ```registry.json``` file, then ```github:spoonx/aurelia-notification```, because it always installs ```github:MarcScheib/aurelia-notification``` (at least on my machine). But that would end up in a fight around who can get it's line the lowest in the ```registry.json``` file :-)
***
If i looked this up correctly ```github:MarcScheib/aurelia-notification``` was first in the file:

github:MarcScheib/aurelia-notification was added https://github.com/jspm/registry/commit/b8a4dcf93b3218040a9f923b8882eedf02f49bac at Sat Feb 13 13:14:15 2016 +0100

github:spoonx/aurelia-notification was added https://github.com/jspm/registry/commit/92700174b9bc08b316d4051d0ce55d49cfd2169e at Thu Mar 24 11:32:22 2016 +0100

So in this case, remove ```github:spoonx/aurelia-notification```, because it was added later on.
***
If we lookup [aurelia-notification on npmjs](https://www.npmjs.com/package/aurelia-notification) then it points to ```github:spoonx/aurelia-notification```. I am not sure if one would expect when performing ```jspm i aurelia-notification``` to install ```npm:aurelia-notification``` or that it could be expected to be installing another package.
***
There is not much information to gather from the repositories itself:

* Both of the git repositories look like there is active development on them in the past few days.
* One has 5 stars more then the other, but that is not a major difference.

***

Maybe the authors of the commits (@MarcScheib and @RWOverdijk) can reach an agreement on which one should be in there, otherwise I would say remove the ```github:spoonx/aurelia-notification``` for now to get a valid ```registry.json``` again.

Reasons for remove: 

- it's never installed anyway (only gets installed if ```github:MarcScheib/aurelia-notification``` is gone)
- was added later on in time according to commit date stamp

That would be a fair judgement for now I think.

**Comment by MarcScheib** [comment]
Hi @eriklieben ,

thank you for your hint. From my perspective, I would remove the spoonx version :laughing: :laughing: 

Just joking: I would propose a rename of one repository. Perhaps you/others have some proposals. 

I had a look at the other repository which seems to be a wrapper around _github:wavded/humane-js_, whereas mine has no external dependencies (except for aurelia internals). So, perhaps a clarification in the name of spoonx' repository would be a good idea. I have mine also listed in the aurelia-registry as _aurelia-notification_. 

However, I will also agree on renaming of mine. I am completely open to community decisions as well.

**Comment by RWOverdijk** [comment]
Oh, that's pretty daft of me. I didn't realize there was another notification lib for aurelia.. I'll hit you up on gitter @MarcScheib. We'll figure something out :)

**Comment by MarcScheib** [comment]
Solved this by renaming ```github:MarcScheib/aurelia-notification``` to ```github:MarcScheib/aurelia-notify``` and leaving ```github:spoonx/aurelia-notification``` as it is.

**Comment by eriklieben** [comment]
Wonderful, thanks!
