### ISSUE TITLE
Help with installing github:fullcalendar/fullcalendar

### ISSUE THREAD

**Issue by hoisel** [jspm/registry#866]
I'm trying to install *github:fullcalendar/fullcalendar* that has dependencies on moment.js.

This is my override, but it seems wrong!

```json
"github:fullcalendar/fullcalendar@2.6.1": {
        "main": "fullcalendar",
        "registry": "jspm",
        "format": "global",
        "files": [
          "lang",
          "fullcalendar",
          "fullcalendar.css"
        ],
        "dependencies": {
            "moment": "^2.12.0"
        }
    }
}
````

![image](https://cloud.githubusercontent.com/assets/400244/14401193/13e2be18-fddf-11e5-923a-b5e9136bdfb0.png)

*moment.js* gets installed(from npm) as a dependency from fullcalendar but the above error is shown.

The config.js file and *jspm_packages* folder are:

![image](https://cloud.githubusercontent.com/assets/400244/14401277/892d3830-fde2-11e5-9959-be4e9cf3fd61.png)

**Comment by guybedford** [comment]
See for an example of an override using moment - https://github.com/jspm/registry/blob/ac6b7c17ae73f13b451bc6f7f647553a7e527e6b/package-overrides/github/nnnick/Chart.js%402.0.0-beta2.json.

Note that `dependencies` and shim `deps` are both needed. The first tells jspm to install moment when installing the fullcalendar, the second tells SystemJS to load moment before loading fullcalendar.

**Comment by hoisel** [comment]
Thank you @guybedford.
After diving into fullcalendar source code I discovered that FullCalendar was written in CJS format, so I just changed format property to CJS(instead global) and it worked.

```javascript
if (typeof define === 'function' && define.amd) {
     define([ 'jquery', 'moment' ], factory);
		}
		else if (typeof exports === 'object') { // Node/CommonJS
			module.exports = factory(require('jquery'), require('moment'));
		}
		else {
			factory(jQuery, moment);
		}
	})(function($, moment) {
```

**Comment by hoisel** [comment]
update:
As fullcalendar is in cjs format, I just re-installed it from npm and no more overrides needed.
