### ISSUE TITLE
Latest Dogfalo/materialize override breaks install

### ISSUE THREAD

**Issue by clintharris** [jspm/registry#877]
@guybedford: the [recent changes](https://github.com/jspm/registry/commit/52fcf0f0056f08592bb42babf0c81988ff180fe1) to github/Dogfalo/materialize@0.97.5.json seems to have broken something...
```
$ jspm install github:Dogfalo/materialize@0.97.6
     Looking up github:Dogfalo/materialize
     Updating registry cache...

warn Error on locate for github:jquery
     GitHub packages must be of the form owner/repo.

warn Error on locate for github:css
     GitHub packages must be of the form owner/repo.

err  Error: Error locating github:jquery.
         at /private/tmp/ogp-web-ui/node_modules/systemjs-builder/lib/builder.js:23:9
         at Object.lib$rsvp$events$$default.trigger (/private/tmp/ogp-web-ui/node_modules/rsvp/dist/rsvp.js:245:13)
         at null._onTimeout (/private/tmp/ogp-web-ui/node_modules/rsvp/dist/rsvp.js:568:47)
         at Timer.listOnTimeout (timers.js:92:15)

err  Error locating github:jquery.

warn Installation changes not saved.
```
node 5.0.0
npm 3.3.9
jspm 0.16.11

**Comment by guybedford** [comment]
Thanks, I've added a fix in https://github.com/jspm/registry/commit/39533aef79b7797b6fc2a6aab13a0f495fcea158. Let me know if that helps.

Note that this was done to conslidate the jquery version, so you may need to override this behaviour, but we do need to ensure the ecosystem is consistent.

In jspm 0.17 overrides can't break like this through these types of updates as they persist in the package.json.

**Comment by clintharris** [comment]
Fixed--thanks for the fast response!
