### ISSUE TITLE
amd format and main is not considered

### ISSUE THREAD

**Issue by karthickthangasamy** [jspm/registry#882]
I have the below configuration for the existing github repository which was published in bower. I am trying to configure the same for JSPM package installation. The `pacakge.json` file contains the below setup. But the `format amd` is not considered at all.

        "jspm": {
        "main": "false",
        "format": "amd",        
        "shim": {
            "Scripts/**/*": {
                "deps": [
                    "jquery",
                    "jquery-easing",
                    "jsrender"
                ]                
            }
        },
        "files": [
            "Scripts",
            "Content"
        ],
        "dependencies": {
            "jquery": "npm:jquery@^2.2.3",
            "jquery-easing": "npm:jquery.easing@^1.3.2",
            "jsrender": "npm:jsrender@^0.9.75"
        }
    }`

The source files which was present in the `Scripts` folder defined with `amd` config references for internal file references. But the downloaded files using `jspm install test=github:test` was added with `global` format for all the scripts files.

/* */ 
"format global";
"deps jquery";
"deps jquery-easing";
"deps jsrender";

**Comment by guybedford** [comment]
When using the shim property, it overrides the format property, treating shimed modules as global modules. jspm 0.17 doesn't have this restriction, allowing `{ meta: { "scripts/*.js": { deps: ["jquery", ...] } } }` to work alongside the format metadata. Perhaps this would be a reason to consider upgrading.

**Comment by karthickthangasamy** [comment]
@guybedford Thanks for the information. I tried the above `meta` config in `package.json` file but the deps not added for scripts source which was download from github, which was added while including the `shim` config. This same config(`meta`) is equivalent to removing the `shim` config from `package.json`.  But the amd request for internal files working as expected.

**Comment by guybedford** [comment]
@karthickthangasamy note it is case sensitive and that only applies in jspm 0.17. It does work honest! Just let me know if you have any further questions.

**Comment by karthickthangasamy** [comment]
@guybedford I have removed `meta` and `shim` config from `package.json` file which works as expected. But the downloaded script source files doesn't have any `format` as mentioned earlier in this thread.
