### ISSUE TITLE
use minified version of libraries when using HTTP2 

### ISSUE THREAD

**Issue by timtimmytime** [jspm/registry#888]
Since there is no need to make bundles with http2, is it posible that jspm / systemJS loads the .min version of libraries from the /jspm_packages/ directory instead of the normal version?

for example "angular.min.js" instead of "angular.js"

perhaps when running `jspm depcache` it could cause a re-mapping to .min. versions?

**Comment by guybedford** [comment]
Using minified files directly creates a bad experience for development as source maps often have subtle issues. If source maps were perfect this would make a lot of sense, and was how we did things originally, but the focus is rather on production-time minification due to these issues.
