### ISSUE TITLE
Getting an error when installing npm:materialize-css

### ISSUE THREAD

**Issue by rubyboy** [jspm/registry#891]
```jspm install npm:materialize-css``` results in:
```
warn Error on processPackageConfig
     Package.json dependency jquery set to github:components/jquery, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

warn Error processing package config for npm:materialize-css.

err  Error processing package config for npm:materialize-css.

warn Installation changes not saved.
```

I'm using the latest (non-beta) JSPM version 0.16.34

I can fix that by adding the following flag to the override.json: ```"jspmNodeConversion": false``` . Will create a PR for it. Hopefully that's the right way around the problem of importing Github dependencies from NPM ones.

**Comment by guybedford** [comment]
That is fine in this case as the package doesn't seem to be CommonJS anyway so we can skip the conversion. Thanks for sorting it out.
