### ISSUE TITLE
ui-router-extras is named angular-ui-router-extras in jspm registry

### ISSUE THREAD

**Issue by christopherthielen** [jspm/registry#893]
So after making that PR for ui-router, I noticed that `ui-router-extras` is named `angular-ui-router-extras` on [jspm registry](https://github.com/jspm/registry/blob/master/registry.json#L91).  Shall I make a PR to rename it?  

The package is named `ui-router-extras` on both [bower](https://github.com/christopherthielen/ui-router-extras/blob/master/bower.json#L2) and [npm](https://github.com/christopherthielen/ui-router-extras/blob/master/package.json#L3).

**Comment by guybedford** [comment]
Sure I've added https://github.com/jspm/registry/commit/c6061745727674a0500ad50ca22e7cb2f638f9ba. It's ok to have some duplicates in the registry. Let me know if that sounds ok to you.
