### ISSUE TITLE
caniuse-api trying to load json files without providing an extension

### ISSUE THREAD

**Issue by alexisvincent** [jspm/registry#908]
caniuse-api is trying to load json files without providing an extension, not quite sure how to override this?

**Comment by guybedford** [comment]
This can be done with:

```
map: {
  './path/to/json': './path/to/json.json'
}
```

That can go in the package config file (`jspm_packages/npm/caniuse-api@1.2.3.json`) or the override itself.

**Comment by alexisvincent** [comment]
Thanks!
Once I've written out working overrides can we get this into the registry? Anyone wanting to get postcss working is going to hit this issue

**Comment by guybedford** [comment]
Sure, although I'm not sure how the overrides will help given the postinstall script reliance?

**Comment by alexisvincent** [comment]
Damn. I forgot, there's two issues here. The postInstall and an then the json extensions. I forgot about the postInstall
