### ISSUE TITLE
Shim CSS files

### ISSUE THREAD

**Issue by Baudin999** [jspm/registry#925]
I can't seem to solve the following requirement:

I use the package [phosphorJS](http://phosphorjs.github.io/) and I'm trying to load the package with JSPM. I've found the following line in the source code of the package:

```javascript
require('./index.css');
```

This seems to result in a call to:

```
GET http://localhost:4003/jspm_packages/npm/phosphor-dockpanel@0.9.7/lib/index.css.js
```

Is there a way to either intercept this call or maybe point it to right file? (I am quite new to JSPM.) Thank you for your help!

**Comment by guybedford** [comment]
You can configure css files to load as css by using the css plugin.

This can be done via `jspm install css` and then adding the configuration:

```javascript
System.config({
  meta: {
    'npm:phosphor-dockpanel@0.9.7/*.css': { loader: 'css' }
  }
});
```

A more modular approach can be achieved by using override configuration:

```
jspm install npm:phosphor-dockpanel@0.9.7 -o "{meta:{'./lib/index.css': {loader:'css'}}}"
```

Although the above will only work in jspm 0.17.

**Comment by Baudin999** [comment]
Thank you very much for the extra information. This answer solves the problem!
