### ISSUE TITLE
Is JSPM dependant on GIT being installed?

### ISSUE THREAD

**Issue by chrisfwd** [jspm/registry#959]
This may be a stupid question but we're trying to get a TFS build working with JSPM but when we run jspm install on the server we get an error "git not installed". Does git need to be installed in order for jspm to pull projects from github?

**Comment by guybedford** [comment]
Yes, you do need to have git installed with the `git` bin available in the environment.

**Comment by chrisfwd** [comment]
Thank you for the quick response @guybedford
