### ISSUE TITLE
Latest version of React (15.3.1) 404s on a file

### ISSUE THREAD

**Issue by simondiep** [jspm/registry#963]
I'm running into a 404 trying to load React without specifying a version.

`import React from 'react';`

GET https://npm.jspm.io/react@15.3.1/lib/accumulateInto.js 404 (Not Found)

I don't explicitly specify this file, but it tries to get loaded.

I've noticed the previous version's file is there [15.3.0](https://npm.jspm.io/react@15.3.0/lib/accumulateInto.js).

For more info, see my [barebones project](https://github.com/simondiep/minimal-react-example/blob/jspm/components/hello-world.js).

**Comment by guybedford** [comment]
Thanks for spotting this. It should be working now.
