### ISSUE TITLE
0.17.0-beta.28: JSDOM import fails

### ISSUE THREAD

**Issue by m-a-r-c-e-l-i-n-o** [jspm/registry#970]
JSPM fails to import [jsdom](https://github.com/tmpvar/jsdom) because [it doesn't seem to realize (appropriately so) that one of its dependencies ("canvas", in this case) is conditional](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/utils.js#L233-L242) and fatally complains that it is not found. I don't actually need the dependency, I just want jspm (or likely SystemJS, in this case) to ignore it. Alternatively, installing the dependency causes another issue within the dependency itself, but likely not worth investigating, for now. Any guidance on how to resolve this would be highly appreciated.

**Comment by guybedford** [comment]
You can avoid this with:

```javascript
System.config({
  map: {
    canvas: '@empty'
  }
});
```

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Not sure how I missed that in the [docs](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#map), thank you, guy.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Not sure how I missed that in the [docs](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#map), thank you, guy.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Not sure how I missed that in the [docs](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#map), thank you, guy.
