### ISSUE TITLE
angular-strap

### ISSUE THREAD

**Issue by dhultgren** [jspm/registry#995]
I get a 404 on tooltip/tooltip.tpl.html. I found [this](https://github.com/jspm/registry/issues/160) and that specific version of angular-strap does work, but others don't. It's fairly old by now and it would be nice to be able to use a recent version without hacks. Can you make that override affect all versions?

**Comment by guybedford** [comment]
If you're able to suggest any changes to the override at https://github.com/jspm/registry/issues/161 that need to be introduced that would help here.

That override will still be applying for the latest version, it just sounds like it is now out of date.

**Comment by dhultgren** [comment]
This was an issue with angular-strap. Thank you for your help!
